// Code generated by scripts/generate-constants. DO NOT EDIT.

export const EddingtonNextSteps = 5
export const ImportEventBatchSize = 25
export const ImportEventFlushIntervalMs = 2000
export const PaginationDefaultPage = 1
export const PaginationDefaultPerPage = 50
export const PaginationMaxPage = 10000
export const PaginationMaxPerPage = 200
export const PowerDurationsS = [5, 10, 30, 60, 300, 480, 1200, 3600] as const
export const TrainingLoadAtlTauDays = 7
export const TrainingLoadCtlTauDays = 42
