// Code generation script for shared constants.
// Reads shared/constants.json and generates:
// - internal/shared/constants.gen.go
// - web/src/lib/shared/constants.gen.ts
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := findProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding project root: %v\n", err)
		os.Exit(1)
	}

	input := filepath.Join(root, "shared", "constants.json")
	goOutput := filepath.Join(root, "internal", "shared", "constants.gen.go")
	tsOutput := filepath.Join(root, "web", "src", "lib", "shared", "constants.gen.ts")

	raw, err := os.ReadFile(input) //nolint:gosec // G304: path is controlled
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading constants: %v\n", err)
		os.Exit(1)
	}

	var values map[string]any
	if err := json.Unmarshal(raw, &values); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing constants: %v\n", err)
		os.Exit(1)
	}

	if err := generateGoConstants(values, goOutput); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating Go constants: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated: %s\n", goOutput)

	if err := generateTSConstants(values, tsOutput); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating TS constants: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated: %s\n", tsOutput)
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod")
		}
		dir = parent
	}
}

func generateGoConstants(values map[string]any, output string) error {
	keys := sortedKeys(values)

	var constLines []string
	var varLines []string

	for _, key := range keys {
		value := values[key]
		if arr, ok := value.([]any); ok {
			ints, isInt := toIntSlice(arr)
			if !isInt {
				floats := toFloatSlice(arr)
				varLines = append(varLines, fmt.Sprintf("%s = []float64{%s}", key, joinFloatSlice(floats)))
				continue
			}
			varLines = append(varLines, fmt.Sprintf("%s = []int{%s}", key, joinIntSlice(ints)))
			continue
		}
		if num, ok := value.(float64); ok {
			constLines = append(constLines, fmt.Sprintf("%s = %s", key, formatNumber(num)))
			continue
		}
		return fmt.Errorf("unsupported constant type for %s", key)
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/generate-constants. DO NOT EDIT.\n\n")
	buf.WriteString("package shared\n\n")

	if len(constLines) > 0 {
		buf.WriteString("const (\n")
		for _, line := range constLines {
			buf.WriteString("\t" + line + "\n")
		}
		buf.WriteString(")\n\n")
	}

	if len(varLines) > 0 {
		buf.WriteString("var (\n")
		for _, line := range varLines {
			buf.WriteString("\t" + line + "\n")
		}
		buf.WriteString(")\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting Go output: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil { //nolint:gosec // G301
		return fmt.Errorf("creating output dir: %w", err)
	}
	return os.WriteFile(output, formatted, 0o644) //nolint:gosec // G306
}

func generateTSConstants(values map[string]any, output string) error {
	keys := sortedKeys(values)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by scripts/generate-constants. DO NOT EDIT.\n\n")

	for _, key := range keys {
		value := values[key]
		if arr, ok := value.([]any); ok {
			ints, isInt := toIntSlice(arr)
			if isInt {
				fmt.Fprintf(&buf, "export const %s = [%s] as const\n", key, joinIntSlice(ints))
				continue
			}
			floats := toFloatSlice(arr)
			fmt.Fprintf(&buf, "export const %s = [%s] as const\n", key, joinFloatSlice(floats))
			continue
		}
		if num, ok := value.(float64); ok {
			fmt.Fprintf(&buf, "export const %s = %s\n", key, formatNumber(num))
			continue
		}
		return fmt.Errorf("unsupported constant type for %s", key)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil { //nolint:gosec // G301
		return fmt.Errorf("creating output dir: %w", err)
	}
	return os.WriteFile(output, buf.Bytes(), 0o644) //nolint:gosec // G306
}

func sortedKeys(values map[string]any) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func formatNumber(num float64) string {
	if math.Mod(num, 1) == 0 {
		return fmt.Sprintf("%.0f", num)
	}
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", num), "0"), ".")
}

func toIntSlice(arr []any) ([]int, bool) {
	ints := make([]int, 0, len(arr))
	for _, item := range arr {
		num, ok := item.(float64)
		if !ok || math.Mod(num, 1) != 0 {
			return nil, false
		}
		ints = append(ints, int(num))
	}
	return ints, true
}

func toFloatSlice(arr []any) []float64 {
	floats := make([]float64, 0, len(arr))
	for _, item := range arr {
		num, ok := item.(float64)
		if !ok {
			return nil
		}
		floats = append(floats, num)
	}
	return floats
}

func joinIntSlice(values []int) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = fmt.Sprintf("%d", v)
	}
	return strings.Join(parts, ", ")
}

func joinFloatSlice(values []float64) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = formatNumber(v)
	}
	return strings.Join(parts, ", ")
}
