// Code generation script for SQL schema.
// Parses schema/migrations/*.sql files and generates:
// - web/src/lib/wasm/db/schema.gen.ts (TypeScript migrations for browser)
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// Find project root (where go.mod is)
	root, err := findProjectRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding project root: %v\n", err)
		os.Exit(1)
	}

	migrationsDir := filepath.Join(root, "schema", "migrations")
	output := filepath.Join(root, "web", "src", "lib", "wasm", "db", "schema.gen.ts")

	// Read all migration files
	migrations, err := readMigrations(migrationsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading migrations: %v\n", err)
		os.Exit(1)
	}

	// Generate TypeScript
	if err := generateTS(migrations, output); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating TypeScript: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated: %s (%d migrations)\n", output, len(migrations))
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod")
		}
		dir = parent
	}
}

type Migration struct {
	Version int
	Name    string
	SQL     string
}

func readMigrations(dir string) ([]Migration, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading directory: %w", err)
	}

	var migrations []Migration
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".sql") {
			continue
		}

		// Parse version from filename (e.g., "001_initial.sql" -> 1)
		var version int
		var name string
		_, err := fmt.Sscanf(entry.Name(), "%03d_%s", &version, &name)
		if err != nil {
			// Try without leading zeros
			_, err = fmt.Sscanf(entry.Name(), "%d_%s", &version, &name)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: skipping %s (invalid format)\n", entry.Name())
				continue
			}
		}
		name = strings.TrimSuffix(name, ".sql")

		content, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", entry.Name(), err)
		}

		migrations = append(migrations, Migration{
			Version: version,
			Name:    name,
			SQL:     string(content),
		})
	}

	// Sort by version
	sort.Slice(migrations, func(i, j int) bool {
		return migrations[i].Version < migrations[j].Version
	})

	return migrations, nil
}

func generateTS(migrations []Migration, output string) error {
	var sb strings.Builder

	sb.WriteString(`// Code generated by scripts/generate-schema. DO NOT EDIT.

/**
 * Database migrations for browser WASM mode.
 * These are embedded at build time from schema/migrations/*.sql
 */

export interface Migration {
  version: number
  name: string
  sql: string
}

export const migrations: Migration[] = [
`)

	for i, m := range migrations {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  {\n"))
		sb.WriteString(fmt.Sprintf("    version: %d,\n", m.Version))
		sb.WriteString(fmt.Sprintf("    name: %q,\n", m.Name))
		sb.WriteString(fmt.Sprintf("    sql: `%s`,\n", escapeForTS(m.SQL)))
		sb.WriteString(fmt.Sprintf("  }"))
	}

	sb.WriteString("\n]\n")

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	return os.WriteFile(output, []byte(sb.String()), 0644)
}

func escapeForTS(s string) string {
	// Escape backticks and ${} for template literals
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}
