// Code generated by scripts/generate-go-storage. DO NOT EDIT.
//
// This file contains TypeScript declarations for the Go WASM storage layer.
// The goStorage global object is registered by the Go WASM binary at runtime.
//
// To regenerate: just generate-go-storage

/**
 * Go WASM storage interface.
 * All methods are synchronous and return JSON strings (except exportDb).
 * Parse results with JSON.parse() and check for errors.
 */
export interface GoStorageInterface {

  // Algorithms - Training Load
  /** Algorithm Functions - Training Load */
  calculateTrainingLoad(dailyTss: number[], ctlTau: number, atlTau: number): string

  // Other
  /** calculateTrainingLoadWithInitialFn calculates training load from existing CTL/ATL */
  calculateTrainingLoadWithInitial(dailyTss: number[], initialCtl: number, initialAtl: number, ctlTau: number, atlTau: number): string
  /** cancelImport cancels the currently running import. */
  cancelImport(): string
  /** clearImportState clears the saved import state. */
  clearImportState(): string
  /** completeSyncRun marks a sync run as complete */
  completeSyncRun(dataJSON: string): string
  /** createCustomGear creates a new custom gear item */
  createCustomGear(gearJSON: string): string
  /** deleteComponent deletes a component */
  deleteComponent(id: number): string
  /** deleteCustomGear deletes a custom gear item */
  deleteCustomGear(deleteJSON: string): string
  /** deleteHrZoneDefinition deletes an HR zone definition */
  deleteHrZoneDefinition(deleteJSON: string): string
  /** deleteStravaCredentials removes stored Strava API credentials */
  deleteStravaCredentials(): string
  /** eddingtonHistoryFn calculates progressive Eddington numbers over time */
  eddingtonHistory(distances: number[]): string
  /** eddingtonNextStepsFn calculates days needed for next Eddington numbers */
  eddingtonNextSteps(distances: number[], currentE: number, stepsToCalculate: number): string
  /** exportDatabase exports the database for OPFS persistence */
  exportDb(): Uint8Array
  /** getFtpRunningHistory returns FTP history for running */
  getFtpRunningHistory(): string
  /** getImportProgress returns the current import progress. */
  getImportProgress(): string
  /** getImportState loads the saved import state for resume capability. */
  getImportState(): string
  /** getWeightHistory returns weight history */
  getWeightHistory(): string
  /** hasStravaCredentials checks if credentials are configured */
  hasStravaCredentials(): string
  /** intensityFactorFn calculates the intensity factor: IF = NP / FTP */
  intensityFactor(np: number, ftp: number): string
  /** isImportRunning returns whether an import is currently running. */
  isImportRunning(): string
  /** logMaintenance logs a maintenance event for a component */
  logMaintenance(logJSON: string): string
  /** predictAfterWorkoutFn calculates predicted TSB after a planned workout */
  predictAfterWorkout(currentCtl: number, currentAtl: number, plannedTss: number, ctlTau: number, atlTau: number): string
  /** rollingMaxAverageFn finds the maximum rolling average over a given window */
  rollingMaxAverage(values: number[], windowSeconds: number): string
  /** saveStravaCredentials stores Strava API credentials */
  saveStravaCredentials(credentialsJSON: string): string
  /** setAthleteID sets the current athlete ID for queries */
  setAthleteId(id: number): string
  /** trainingStressScoreFn calculates TSS */
  trainingStressScore(durationSeconds: number, np: number, ftp: number): string
  /** tssForTargetTsbFn calculates TSS needed to reach a target TSB */
  tssForTargetTsb(currentCtl: number, currentAtl: number, targetTsb: number, ctlTau: number, atlTau: number): string
  /** updateAppSettings updates the athlete's app settings */
  updateAppSettings(settingsJSON: string): string
  /** updateCustomGear updates an existing custom gear item */
  updateCustomGear(gearJSON: string): string
  /** updateFtpHistory replaces FTP history */
  updateFtpHistory(entriesJSON: string): string
  /** updateFtpRunningHistory replaces running FTP history */
  updateFtpRunningHistory(entriesJSON: string): string
  /** updateSyncRun updates a sync history record status (for pause/resume) */
  updateSyncRun(dataJSON: string): string
  /** updateTrainingGoals updates training goals config */
  updateTrainingGoals(configJSON: string): string
  /** updateWeightHistory replaces weight history */
  updateWeightHistory(entriesJSON: string): string
  /** upsertHrZoneDefinition creates or updates an HR zone definition */
  upsertHrZoneDefinition(zoneJSON: string): string

  // Power
  /** Standard durations for power curve (matching Go backend and TS importer) */
  computePowerBestEfforts(dataJSON: string): string

  // Maintenance
  /** Maintenance */
  createComponent(arg0?: string): string
  /** genGetGearComponents wraps MaintenanceService.ListComponents */
  getGearComponents(arg0?: string): string
  /** Maintenance */
  getMaintenanceDue(): string
  /** genUpdateComponent wraps MaintenanceService.UpdateComponent */
  updateComponent(arg0?: string): string

  // Sync History - Write
  /** Sync History Write */
  createSyncRun(dataJSON: string): string

  // Algorithms - Eddington
  /** Algorithm Functions - Eddington */
  eddingtonNumber(distances: number[]): string

  // Activities
  /** Activities */
  getActivities(arg0?: string): string
  /** genGetActivity wraps ActivityService.GetByID */
  getActivity(arg0?: string): string
  /** genGetActivityAnalysis wraps ActivityService.GetAnalysis */
  getActivityAnalysis(arg0?: string): string
  /** genGetActivityStreams wraps ActivityService.GetStreams */
  getActivityStreams(arg0?: string): string

  // Photos
  /** Photos */
  getActivityPhotos(arg0?: string): string
  /** genGetPhotos wraps PhotosService.List */
  getPhotos(arg0?: string): string

  // Settings
  /** Settings */
  getAppSettings(): string

  // Auth
  /** Auth */
  getAuthStatus(): string

  // Stats
  /** Stats */
  getBestEffortPRs(arg0?: string): string
  /** genGetBestEffortsForType wraps StatsService.GetBestEffortsForType */
  getBestEffortsForType(arg0?: string): string
  /** genGetEddingtonCompare wraps StatsService.GetEddingtonCompare */
  getEddingtonCompare(): string
  /** genGetEddingtonData wraps StatsService.GetEddingtonData */
  getEddingtonData(arg0?: string): string
  /** genGetEddingtonHistory wraps StatsService.GetEddingtonHistory */
  getEddingtonHistory(arg0?: string): string
  /** genGetHeatmapData wraps StatsService.GetHeatmapData */
  getHeatmapData(arg0?: string): string
  /** genGetInsights wraps InsightsService.GetInsights */
  getInsights(): string
  /** genGetMonthlyComparison wraps StatsService.GetMonthlyComparison */
  getMonthlyComparison(arg0?: string): string
  /** genGetPowerStats wraps StatsService.GetPowerStats */
  getPowerStats(arg0?: string): string
  /** getPowerZones computes time spent in each power zone across all activities */
  getPowerZones(optionalFiltersJSON: string): string
  /** genGetSportGroups wraps StatsService.GetSportGroups */
  getSportGroups(): string
  /** genGetTrainingLoad wraps StatsService.GetTrainingLoad */
  getTrainingLoad(arg0?: string): string
  /** genGetWeeklyTrends wraps StatsService.GetWeeklyTrends */
  getWeeklyTrends(arg0?: string): string
  /** genGetWrapped wraps StatsService.GetWrapped */
  getWrapped(arg0?: string): string
  /** genGetWrappedYears wraps StatsService.GetWrappedYears */
  getWrappedYears(): string
  /** genGetZoneTrend wraps StatsService.GetZoneTrend */
  getZoneTrend(arg0?: string): string

  // Calendar
  /** Calendar */
  getCalendarActivities(arg0?: string): string
  /** genGetCalendarData wraps DashboardService.GetCalendarData */
  getCalendarData(arg0?: string): string
  /** genGetCalendarDataRange wraps DashboardService.GetCalendarDataRange */
  getCalendarDataRange(arg0?: string): string
  /** genGetCalendarSummary wraps DashboardService.GetCalendarSummary */
  getCalendarSummary(arg0?: string): string

  // Challenges
  /** Challenges */
  getChallenges(arg0?: string): string

  // Custom Gear
  /** Custom Gear */
  getCustomGear(filtersJSON: string): string

  // Dashboard
  /** Dashboard */
  getDashboard(): string
  /** genGetDashboardStats wraps DashboardService.GetStats */
  getDashboardStats(): string
  /** genGetMonthlyStats wraps DashboardService.GetMonthlyStats */
  getMonthlyStats(arg0?: string): string
  /** genGetRecentActivities wraps DashboardService.GetRecentActivities */
  getRecentActivities(arg0?: string): string
  /** genGetSportTypeStats wraps DashboardService.GetSportTypeStats */
  getSportTypeStats(): string
  /** genGetWeeklyStats wraps DashboardService.GetWeeklyStats */
  getWeeklyStats(): string
  /** genGetYearlyStats wraps DashboardService.GetYearlyStats */
  getYearlyStats(): string

  // DashboardConfig
  /** DashboardConfig */
  getDashboardConfig(): string
  /** genUpdateDashboardConfig wraps DashboardService.UpdateConfig */
  updateDashboardConfig(arg0?: string): string

  // Distribution
  /** Distribution */
  getDaytimeDistribution(arg0?: string): string
  /** genGetWeekdayDistribution wraps DashboardService.GetWeekdayDistribution */
  getWeekdayDistribution(arg0?: string): string

  // Export
  /** Export */
  getExportStats(): string

  // Athlete - Read
  /** Athlete Read */
  getFirstAthlete(): string

  // Athlete - Metrics
  /** Athlete Metrics (FTP/Weight) */
  getFtpHistory(): string

  // Gear
  /** Gear */
  getGear(arg0?: string): string
  /** genGetGearDetail wraps GearService.GetByID */
  getGearDetail(arg0?: string): string
  /** genGetGearMonthlyUsage wraps GearService.MonthlyUsage */
  getGearMonthlyUsage(arg0?: string): string
  /** genUpdateGearPrice wraps GearService.UpdateGearPrice */
  updateGearPrice(arg0?: string): string

  // HR Zones
  /** HR Zones */
  getHrZoneDefinitions(): string

  // Segment Efforts
  /** Segment Countries (no generated version - uses ListCountries directly) */
  getSegmentCountries(): string

  // Segments
  /** Segments */
  getSegmentDetail(arg0?: string): string
  /** genGetSegmentEfforts wraps SegmentsService.ListEfforts */
  getSegmentEfforts(arg0?: string): string
  /** genGetSegments wraps SegmentsService.List */
  getSegments(arg0?: string): string

  // App State - Credentials
  /** Strava Credentials */
  getStravaCredentials(): string

  // Sync History - Read
  /** Sync History Read */
  getSyncHistory(limit?: number): string

  // Training Goals
  /** Training Goals */
  getTrainingGoals(year?: number): string

  // Initialization
  /** Initialization */
  init(): string

  // Algorithms - Power
  /** Algorithm Functions - Power */
  normalizedPower(watts: number[]): string

  // Activities-Write
  /** Activities-Write */
  saveActivity(arg0?: string): string
  /** genSaveStream wraps ActivityService.SaveStream */
  saveStream(arg0?: string): string

  // Athlete - Write
  /** Athlete Write */
  saveAthlete(athleteJSON: string): string

  // BestEfforts-Write
  /** BestEfforts-Write */
  saveBestEfforts(arg0?: string): string

  // Gear-Write
  /** Gear-Write */
  saveGear(arg0?: string): string

  // Photos-Write
  /** Photos-Write */
  savePhoto(arg0?: string): string

  // Segments-Write
  /** Segments-Write */
  saveSegment(arg0?: string): string
  /** genSaveSegmentEffort wraps SegmentsService.SaveSegmentEffort */
  saveSegmentEffort(arg0?: string): string

  // Import
  /** Import Control */
  startImport(optionsJSON: string, athleteJSON: string): string
}

/**
 * Global goStorage object registered by Go WASM.
 * Available after WASM initialization.
 */
declare const goStorage: GoStorageInterface

export { goStorage }
