// Code generated by scripts/generate-go-storage. DO NOT EDIT.
//
// This file contains TypeScript declarations for the Go WASM storage layer.
// The goStorage global object is registered by the Go WASM binary at runtime.
//
// To regenerate: just generate-go-storage

/**
 * Go WASM storage interface.
 * All methods are synchronous and return JSON strings (except exportDb).
 * Parse results with JSON.parse() and check for errors.
 */
export interface GoStorageInterface {
}

/**
 * Global goStorage object registered by Go WASM.
 * Available after WASM initialization.
 */
declare const goStorage: GoStorageInterface

export { goStorage }
