// Code generated by scripts/generate-ts-types. DO NOT EDIT.
//
// This file contains TypeScript interfaces that match the JSON serialization
// format used by the Go WASM bridge. These types should be used for all
// communication between TypeScript and Go WASM.
//
// To regenerate: just generate-ts-types

// ============================================================================
// From activities.go
// ============================================================================

export interface GetActivitiesRequest {
  page: number
  per_page: number
  sport_type: string
  after: string
  before: string
  gear_id: string
  commute?: boolean | null
  trainer?: boolean | null
  search: string
}

export interface SaveActivityInput {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
  description: string
  device_name: string
  trainer: boolean
  private: boolean
  kudos_count: number
  photo_count: number
}

export interface SaveStreamInput {
  activity_id: number
  stream_type: string
  data: unknown
  series_type: string
  original_size: number
  resolution: string
}

// ============================================================================
// From athletes.go
// ============================================================================

export interface SaveAthleteInput {
  id: number
  username: string
  firstname: string
  lastname: string
  profile_medium: string
  profile: string
  city: string
  state: string
  country: string
  sex: string
  premium: boolean
  summit: boolean
}

// ============================================================================
// From challenges.go
// ============================================================================

export interface GetChallengesRequest {
  month: string
  page: number
  per_page: number
}

// ============================================================================
// From dashboard.go
// ============================================================================

export interface GetHeatmapDataRequest {
  sport_type: string
  year: number
  commute?: boolean | null
}

// ============================================================================
// From gear.go
// ============================================================================

export interface GetGearMonthlyUsageRequest {
  include_retired: boolean
}

export interface GetGearRequest {
  include_retired: boolean
  page: number
  per_page: number
}

export interface SaveGearInput {
  id: string
  athlete_id: number
  name: string
  primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
}

// ============================================================================
// From maintenance.go
// ============================================================================

export interface CreateComponentInput {
  gear_id: string
  name: string
  image_url: string
  maintenance_hashtag: string
  type: string
  threshold_value: number
}

export interface CreateCustomGearInput {
  name: string
  hashtag: string
  retired: boolean
  purchase_price?: number | null
  purchase_currency: string
}

export interface DeleteCustomGearRequest {
  id: string
  force: boolean
}

export interface DeleteHRZoneDefinitionRequest {
  sport_type: string
  effective_from: string
}

export interface GetCustomGearRequest {
  include_retired: boolean
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

export interface GetGearComponentsRequest {
  gear_id: string
  page: number
  per_page: number
}

export interface LogMaintenanceRequest {
  component_id: number
  activity_id?: number | null
  completed_at: string
}

export interface UpdateComponentInput {
  id: number
  name?: string | null
  image_url?: string | null
  maintenance_hashtag?: string | null
  type: string
  threshold_value: number
}

export interface UpdateCustomGearInput {
  id: string
  name?: string | null
  hashtag?: string | null
  retired?: boolean | null
  purchase_price?: unknown | null
  purchase_currency?: string | null
}

export interface UpsertHRZoneDefinitionRequest {
  sport_type: string
  effective_from: string
  method: string
  zones: unknown
}

// ============================================================================
// From photos.go
// ============================================================================

export interface GetPhotosRequest {
  page: number
  per_page: number
}

export interface SavePhotoInput {
  id: string
  athlete_id: number
  activity_id: number
  url: string
  thumbnail_url: string
  caption: string
  location: string
  created_at: string
}

// ============================================================================
// From segments.go
// ============================================================================

export interface GetSegmentEffortsRequest {
  segment_id: number
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

export interface GetSegmentsRequest {
  page: number
  per_page: number
  starred?: boolean | null
  search: string
}

export interface SaveSegmentEffortInput {
  id: number
  segment_id: number
  activity_id: number
  athlete_id: number
  name: string
  elapsed_time: number
  moving_time: number
  start_date: string
  start_date_local: string
  distance: number
  average_watts?: number | null
  average_heartrate?: number | null
  max_heartrate?: number | null
  pr_rank?: number | null
}

export interface SaveSegmentInput {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade: number
  maximum_grade: number
  elevation_high: number
  elevation_low: number
  climb_category: number
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  starred: boolean
  polyline: string
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date: string
}

// ============================================================================
// From stats.go
// ============================================================================

export interface ComputePowerBestEffortsInput {
  activity_id: number
  athlete_id: number
}

export interface GetEddingtonDataRequest {
  sport_types: string[]
}

export interface GetPowerStatsRequest {
  durations: number[]
  after: string
  before: string
  sport_types: string[]
  history_duration: number
}

export interface GetTrainingLoadRequest {
  after: string
  before: string
}

export interface SaveBestEffortsInput {
  athlete_id: number
  activity_id: number
  sport_type: string
  distance_type: string
  name: string
  distance_m: number
  elapsed_time: number
  moving_time?: number | null
  start_index?: number | null
  end_index?: number | null
  pr_rank?: number | null
  start_date: string
}

// ============================================================================
// From sync.go
// ============================================================================

export interface CompleteSyncRunRequest {
  id: number
  status: string
  error: string
  activities_total: number
  activities_imported: number
  activities_skipped: number
  gear_imported: number
  streams_imported: number
  segments_imported: number
  photos_imported: number
  failed_count: number
  newest_activity_date: string
}

export interface CreateSyncRunInput {
  athlete_id: number
  full_sync: boolean
  skip_streams: boolean
  skip_segments: boolean
  skip_best_efforts: boolean
  skip_photos: boolean
}

export interface UpdateSyncRunInput {
  id: number
  status: string
  activities_total: number
  activities_imported: number
  streams_imported: number
  failed_count: number
  newest_activity_date: string
}

