// Code generated by scripts/generate-ts-types (AST-based). DO NOT EDIT.
//
// This file contains TypeScript interfaces that match the JSON serialization
// format used by the Go WASM bridge. These types should be used for all
// communication between TypeScript and Go WASM.
//
// To regenerate: just generate-ts-types

// ============================================================================
// From activities.go
// ============================================================================

/** ActivityItem represents an activity in responses. */
export interface ActivityItem {
  id: number
  name: string
  description?: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone?: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  elev_high?: number | null
  elev_low?: number | null
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  kudos_count: number
  comment_count: number
  photo_count: number
  commute: boolean
  private: boolean
  trainer: boolean
  workout_type?: number | null
  device_name?: string
  gear_id?: string
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  summary_polyline?: string
  location_city?: string
  location_country?: string
}

/** ActivityStreamItem represents a stream in responses. */
export interface ActivityStreamItem {
  activity_id: number
  stream_type: string
  original_size: number
  resolution: string
  series_type: string
  data: unknown
}

/** ActivityTotals represents aggregate statistics. */
export interface ActivityTotals {
  count: number
  distance: number
  moving_time: number
  elapsed_time: number
  elevation: number
  calories: number
  kilojoules: number
}

/** GetActivityInput contains parameters for getting a single activity. */
export interface GetActivityInput {
  activity_id: number
}

/** GetActivityStreamsInput contains parameters for getting activity streams. */
export interface GetActivityStreamsInput {
  activity_id: number
}

/** ListActivitiesInput contains parameters for listing activities. */
export interface ListActivitiesInput {
  sport_types: string[]
  after?: string | null
  before?: string | null
  gear_id: string
  commute?: boolean | null
  trainer?: boolean | null
  search: string
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListActivitiesOutput contains a paginated list of activities. */
export interface ListActivitiesOutput {
  data: ActivityItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

/** SaveActivityInput contains parameters for saving an activity. */
export interface SaveActivityInput {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
  description: string
  device_name: string
  trainer: boolean
  private: boolean
  kudos_count: number
  photo_count: number
}

/** SaveActivityOutput contains the result of saving an activity. */
export interface SaveActivityOutput {
  message: string
}

/** SaveStreamInput contains parameters for saving an activity stream. */
export interface SaveStreamInput {
  activity_id: number
  stream_type: string
  data: unknown
  series_type: string
  original_size: number
  resolution: string
}

/** SaveStreamOutput contains the result of saving a stream. */
export interface SaveStreamOutput {
  message: string
}

// ============================================================================
// From app_state.go
// ============================================================================

export interface SaveStravaCredentialsInput {
  client_id: string
  client_secret: string
}

// ============================================================================
// From athlete.go
// ============================================================================

export interface FTPHistoryResponse {
  cycling: MetricPointDTO[]
  running: MetricPointDTO[]
}

export interface MetricPointDTO {
  recorded_at: string
  value: number
}

export interface UpdateFTPRequest {
  cycling: MetricPointDTO[]
  running: MetricPointDTO[]
}

export interface UpdateWeightRequest {
  points: MetricPointDTO[]
}

export interface WeightHistoryResponse {
  points: MetricPointDTO[]
}

// ============================================================================
// From athlete_metrics.go
// ============================================================================

export interface AthleteMetricPoint {
  recorded_at: string
  value: number
}

// ============================================================================
// From athletes.go
// ============================================================================

export interface SaveAthleteInput {
  id: number
  username: string
  firstname: string
  lastname: string
  profile_medium: string
  profile: string
  city: string
  state: string
  country: string
  sex: string
  premium: boolean
  summit: boolean
}

// ============================================================================
// From auth.go
// ============================================================================

/** AthleteInfo contains athlete data for auth status response. */
export interface AthleteInfo {
  id: number
  username: string
  firstname: string
  lastname: string
  city?: string
  state?: string
  country?: string
  profile_medium?: string
  profile?: string
}

/** AuthStatusResponse represents the auth status response. */
export interface AuthStatusResponse {
  authenticated: boolean
  demo_mode?: boolean
  athlete?: AthleteInfo | null
  expires_at?: number
}

// ============================================================================
// From challenges.go
// ============================================================================

export interface Challenge {
  id: string
  athlete_id: number
  name: string
  slug?: string
  badge_url?: string
  local_badge_url?: string
  completion_date?: string | null
  month?: string
  created_at: string
}

/** ChallengeItem represents a challenge item in responses. */
export interface ChallengeItem {
  id: string
  name: string
  slug?: string
  badge_url?: string
  local_badge_url?: string
  completion_date?: string | null
  month?: string
}

export interface GetChallengesRequest {
  month: string
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

export interface ImportBody {
  html: string
  url: string
}

/** ListChallengesInput contains parameters for listing challenges. */
export interface ListChallengesInput {
  month: string
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListChallengesOutput contains a paginated list of challenges. */
export interface ListChallengesOutput {
  data: ChallengeItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

// ============================================================================
// From dashboard.go
// ============================================================================

/** CalendarActivityOutput represents an activity summary for the calendar view. */
export interface CalendarActivityOutput {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  moving_time: number
  total_elevation_gain: number
}

/** CalendarDayOutput represents activity data for a single day. */
export interface CalendarDayOutput {
  date: string
  activity_count: number
  total_distance: number
  total_time: number
  total_calories: number
}

/** CalendarMonthSummaryOutput represents a monthly summary for the calendar. */
export interface CalendarMonthSummaryOutput {
  year: number
  month: number
  activity_count: number
  total_distance: number
  total_elevation_gain: number
  total_moving_time: number
  total_calories: number
  workout_count: number
  challenges_completed: number
}

/** DashboardConfigOutput represents the dashboard configuration. */
export interface DashboardConfigOutput {
  version: number
  widgets: DashboardWidgetConfigOutput[]
}

/** DashboardOutput combines all dashboard data. */
export interface DashboardOutput {
  stats?: DashboardStatsOutput | null
  weekly_stats: WeeklyStatOutput[]
  recent_activities: RecentActivityOutput[]
  sport_type_stats: SportTypeStatOutput[]
}

/** DashboardStatsOutput represents aggregated statistics for the dashboard. */
export interface DashboardStatsOutput {
  total_activities: number
  total_distance: number
  total_moving_time: number
  total_elevation_gain: number
  total_calories: number
  year_activities: number
  year_distance: number
  year_moving_time: number
  year_elevation_gain: number
  month_activities: number
  month_distance: number
  month_moving_time: number
  month_elevation_gain: number
}

/** DashboardWidgetConfigOutput represents a widget configuration. */
export interface DashboardWidgetConfigOutput {
  id: string
  width: number
  height?: number
  hidden: boolean
  settings?: Record<string, unknown>
}

/** DistributionSliceOutput represents a single slice of a distribution. */
export interface DistributionSliceOutput {
  label: string
  count: number
}

/** ExportStatsOutput represents export statistics. */
export interface ExportStatsOutput {
  total_activities: number
  first_activity?: string | null
  last_activity?: string | null
}

/** GetCalendarActivitiesInput contains parameters for getting calendar activities. */
export interface GetCalendarActivitiesInput {
  year: number
  month: number
}

/** GetCalendarDataInput contains parameters for getting calendar data. */
export interface GetCalendarDataInput {
  year: number
}

/** GetDistributionInput contains parameters for distribution queries. */
export interface GetDistributionInput {
  sport_types: string[]
}

/** GetMonthlyStatsInput contains parameters for getting monthly stats. */
export interface GetMonthlyStatsInput {
  year: number
}

/** GetRecentActivitiesInput contains parameters for getting recent activities. */
export interface GetRecentActivitiesInput {
  limit: number
}

/** MonthlyStatOutput represents statistics for a single month. */
export interface MonthlyStatOutput {
  month: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** RecentActivityOutput represents a simplified activity for the dashboard. */
export interface RecentActivityOutput {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  moving_time: number
  elevation_gain: number
  summary_polyline?: string
}

/** SportTypeStatOutput represents statistics for a single sport type. */
export interface SportTypeStatOutput {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** UpdateDashboardConfigInput contains parameters for updating dashboard config. */
export interface UpdateDashboardConfigInput {
  config: DashboardConfigOutput
}

/** WeeklyStatOutput represents statistics for a single sport type in the current week. */
export interface WeeklyStatOutput {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** YearlyStatOutput represents statistics for a single year. */
export interface YearlyStatOutput {
  year: number
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

// ============================================================================
// From dashboard_config.go
// ============================================================================

export interface DashboardConfig {
  version: number
  widgets: DashboardWidgetConfig[]
}

export interface DashboardWidgetConfig {
  id: string
  width: number
  height?: number
  hidden: boolean
  settings?: Record<string, unknown>
}

// ============================================================================
// From gear.go
// ============================================================================

/** CreateCustomGearInput contains parameters for creating custom gear. */
export interface CreateCustomGearInput {
  name: string
  hashtag: string
  retired: boolean
  purchase_price?: number | null
  purchase_currency?: string
}

/** DeleteGearOutput contains the result of a delete operation. */
export interface DeleteGearOutput {
  deleted: boolean
}

/** GearItem represents a gear item in responses. */
export interface GearItem {
  id: string
  name: string
  primary: boolean
  retired: boolean
  distance: number
  brand_name?: string
  model_name?: string
  description?: string
  source: string
  hashtag?: string
  purchase_price?: number | null
  purchase_currency?: string
  activity_count: number
}

/** GetGearInput contains parameters for getting a single gear item. */
export interface GetGearInput {
  gear_id: string
}

/** ListGearInput contains parameters for listing gear. */
export interface ListGearInput {
  include_retired: boolean
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListGearOutput contains a paginated list of gear. */
export interface ListGearOutput {
  data: GearItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

/** MonthlyUsageInput contains parameters for getting monthly gear usage. */
export interface MonthlyUsageInput {
  include_retired: boolean
}

/** SaveGearInput contains parameters for saving gear from Strava. */
export interface SaveGearInput {
  id: string
  athlete_id: number
  name: string
  primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
}

/** SaveGearOutput contains the result of saving gear. */
export interface SaveGearOutput {
  message: string
}

/** UpdateCustomGearInput contains parameters for updating custom gear. */
export interface UpdateCustomGearInput {
  name?: string | null
  hashtag?: string | null
  retired?: boolean | null
  purchase_price?: number | null
  purchase_currency?: string | null
}

// ============================================================================
// From gear_stats.go
// ============================================================================

export interface GearMonthlyUsage {
  month: string
  gear_id: string
  gear_name: string
  source: string
  hashtag?: string
  retired: boolean
  purchase_price?: number | null
  purchase_currency?: string
  activity_count: number
  distance: number
  moving_time: number
}

// ============================================================================
// From goals.go
// ============================================================================

export interface GoalsMetricTargets {
  distance_m?: number | null
  elevation_m?: number | null
  moving_time_s?: number | null
}

export interface GoalsProgress {
  distance_m: number
  elevation_m: number
  moving_time_s: number
  activity_count: number
}

export interface GoalsSportConfig {
  name: string
  sport_types: string[]
  targets: Record<string, GoalsMetricTargets>
}

export interface TrainingGoalsConfig {
  version: number
  sports: GoalsSportConfig[]
}

export interface TrainingGoalsResponse {
  config: TrainingGoalsConfig
  progress: Record<string, Record<string, GoalsProgress>>
}

// ============================================================================
// From health.go
// ============================================================================

/** ErrorResponse represents an error response. */
export interface ErrorResponse {
  error: string
}

/** HealthResponse represents the health check response. */
export interface HealthResponse {
  status: string
}

// ============================================================================
// From import.go
// ============================================================================

export interface StartImportOpts {
  full_sync: boolean
  resume: boolean
  skip_streams: boolean
  skip_segments: boolean
  skip_best_efforts: boolean
  skip_photos: boolean
}

/** StartImportRequest represents a request to start an import. */
export interface StartImportRequest {
  full_sync: boolean
  resume: boolean
  skip_streams: boolean
  skip_segments: boolean
  skip_best_efforts: boolean
  skip_photos: boolean
}

// ============================================================================
// From insights.go
// ============================================================================

/** Insight represents a single coaching insight. */
export interface Insight {
  id: string
  type: string
  severity: string
  title: string
  description: string
}

/** InsightsOutput contains the list of coaching insights. */
export interface InsightsOutput {
  insights: Insight[]
}

// ============================================================================
// From maintenance.go
// ============================================================================

export interface Component {
  id: number
  gear_id: string
  name: string
  image_url?: string
  maintenance_hashtag?: string
  created_at: string
  updated_at: string
}

/** ComponentItem represents a component in responses. */
export interface ComponentItem {
  id: number
  gear_id: string
  name: string
  image_url?: string
  maintenance_hashtag?: string
  created_at: string
  updated_at: string
  last_completed_at?: string | null
  rules: RuleItem[]
}

export interface ComponentWithRules {
  rules: MaintenanceRule[]
  last_completed_at?: string | null
}

/** CreateComponentInput contains parameters for creating a component. */
export interface CreateComponentInput {
  gear_id: string
  name: string
  image_url?: string
  maintenance_hashtag?: string
  rules?: RuleInput[]
}

export interface DeleteCustomGearRequest {
  id: string
  force: boolean
}

export interface DeleteHRZoneDefinitionHRZoneDeleteReq {
  sport_type: string
  effective_from: string
}

export interface DueComponent {
  distance_since: number
  moving_time_since: number
  days_since: number
  progress: RuleProgress[]
  is_due: boolean
}

/** DueComponentItem represents a component with maintenance status. */
export interface DueComponentItem {
  id: number
  gear_id: string
  name: string
  image_url?: string
  maintenance_hashtag?: string
  created_at: string
  updated_at: string
  last_completed_at?: string | null
  rules: RuleItem[]
  distance_since: number
  moving_time_since: number
  days_since: number
  progress: RuleProgressItem[]
  is_due: boolean
}

export interface GetCustomGearRequest {
  include_retired: boolean
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

export interface GetGearComponentsRequest {
  gear_id: string
  page: number
  per_page: number
}

/** ListComponentsInput contains parameters for listing components. */
export interface ListComponentsInput {
  gear_id: string
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListComponentsOutput contains a paginated list of components. */
export interface ListComponentsOutput {
  data: ComponentItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

/** LogMaintenanceInput contains parameters for logging maintenance. */
export interface LogMaintenanceInput {
  component_id: number
  activity_id?: number | null
  completed_at: string
}

export interface LogMaintenanceRequest {
  component_id: number
  activity_id?: number | null
  completed_at: string
}

export interface MaintenanceLogEntry {
  component_id: number
  activity_id?: number | null
  completed_at: string
}

export interface MaintenanceRule {
  id: number
  component_id: number
  type: string
  threshold_value: number
  created_at: string
  updated_at: string
}

/** RuleInput represents a rule in create/update requests. */
export interface RuleInput {
  type: string
  threshold_value: number
}

/** RuleItem represents a maintenance rule in responses. */
export interface RuleItem {
  id: number
  component_id: number
  type: string
  threshold_value: number
}

export interface RuleProgress {
  type: string
  threshold_value: number
  current_value: number
  percent: number
  due: boolean
}

/** RuleProgressItem represents progress for a single rule. */
export interface RuleProgressItem {
  type: string
  threshold_value: number
  current_value: number
  percent: number
  due: boolean
}

/** UpdateComponentInput contains parameters for updating a component. */
export interface UpdateComponentInput {
  component_id: number
  name?: string | null
  image_url?: string | null
  maintenance_hashtag?: string | null
  rules?: RuleInput[]
}

export interface UpsertHRZoneDefinitionHRZoneReq {
  sport_type: string
  effective_from: string
  method: string
  zones: unknown
}

// ============================================================================
// From notifications.go
// ============================================================================

/** TestAllResult represents the result of testing a single notification service. */
export interface TestAllResult {
  serviceId: string
  serviceName: string
  success: boolean
  error?: string
}

/** TestRequest is the request body for testing a single notification service. */
export interface TestRequest {
  serviceId: string
}

/** TestResult is the response for a notification test. */
export interface TestResult {
  success: boolean
  error?: string
}

// ============================================================================
// From photos.go
// ============================================================================

/** ActivityPhotoItem represents a photo attached to an activity. */
export interface ActivityPhotoItem {
  id: string
  activity_id: number
  url: string
  thumbnail_url?: string
  caption?: string
  created_at: string
}

/** FacetItem represents a facet value with count for filtering. */
export interface FacetItem {
  value: string
  iso2?: string
  count: number
}

/** GetActivityPhotosInput contains parameters for getting photos of an activity. */
export interface GetActivityPhotosInput {
  activity_id: number
}

/** ListPhotosInput contains parameters for listing photos. */
export interface ListPhotosInput {
  sport_types: string[]
  country: string
  page: number
  per_page: number
}

/** ListPhotosOutput contains a paginated list of photos with facets. */
export interface ListPhotosOutput {
  data: PhotoItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
  countries: FacetItem[]
  sport_types: FacetItem[]
}

export interface Photo {
  id: string
  athlete_id: number
  activity_id: number
  url: string
  thumbnail_url?: string
  caption?: string
  location?: unknown
  created_at: string
}

export interface PhotoFacetCount {
  value: string
  count: number
}

/** PhotoItem represents a photo in responses. */
export interface PhotoItem {
  id: string
  activity_id: number
  url: string
  thumbnail_url?: string
  caption?: string
  created_at: string
  activity_name: string
  sport_type: string
  start_date_local: string
  location_country?: string
}

export interface PhotoListItem {
  activity_name: string
  sport_type: string
  start_date_local: string
  location_country?: string
}

export interface PhotoListResult {
  items: PhotoListItem[]
  total: number
  countries: PhotoFacetCount[]
  sport_types: PhotoFacetCount[]
}

/** SavePhotoInput contains parameters for saving a photo. */
export interface SavePhotoInput {
  id: string
  athlete_id: number
  activity_id: number
  url: string
  thumbnail_url: string
  caption: string
  location: string
  created_at: string
}

/** SavePhotoOutput contains the result of saving a photo. */
export interface SavePhotoOutput {
  message: string
}

// ============================================================================
// From queries.gen.go
// ============================================================================

/** CountActivitiesByDateRangeRow represents a row returned by CountActivitiesByDateRange. */
export interface CountActivitiesByDateRangeRow {
  count: number
}

/** CountActivitiesBySportAndDateRangeRow represents a row returned by CountActivitiesBySportAndDateRange. */
export interface CountActivitiesBySportAndDateRangeRow {
  count: number
}

/** CountActivitiesBySportRow represents a row returned by CountActivitiesBySport. */
export interface CountActivitiesBySportRow {
  count: number
}

/** CountActivitiesRow represents a row returned by CountActivities. */
export interface CountActivitiesRow {
  count: number
}

/** CountSegmentsByAthleteRow represents a row returned by CountSegmentsByAthlete. */
export interface CountSegmentsByAthleteRow {
  count: number
}

/** GetActiveGearRow represents a row returned by GetActiveGear. */
export interface GetActiveGearRow {
  id: string
  athlete_id: number
  name: string
  is_primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
  source: string
  hashtag: string
  purchase_price?: number | null
  purchase_currency: string
  created_at: string
  updated_at: string
}

/** GetActivitiesByDateRangeRow represents a row returned by GetActivitiesByDateRange. */
export interface GetActivitiesByDateRangeRow {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  suffer_score?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
}

/** GetActivitiesBySportAndDateRangeRow represents a row returned by GetActivitiesBySportAndDateRange. */
export interface GetActivitiesBySportAndDateRangeRow {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  suffer_score?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
}

/** GetActivitiesBySportRow represents a row returned by GetActivitiesBySport. */
export interface GetActivitiesBySportRow {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  suffer_score?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
}

/** GetActivitiesRow represents a row returned by GetActivities. */
export interface GetActivitiesRow {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  suffer_score?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
}

/** GetActivityForZoneComputationRow represents a row returned by GetActivityForZoneComputation. */
export interface GetActivityForZoneComputationRow {
  id: number
  sport_type: string
  start_date: string
}

/** GetActivityIDsWithoutZoneDistributionRow represents a row returned by GetActivityIDsWithoutZoneDistribution. */
export interface GetActivityIDsWithoutZoneDistributionRow {
  id: number
}

/** GetActivityRow represents a row returned by GetActivity. */
export interface GetActivityRow {
  id: number
  athlete_id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  timezone: string
  distance: number
  moving_time: number
  elapsed_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
  average_heartrate?: number | null
  max_heartrate?: number | null
  average_watts?: number | null
  max_watts?: number | null
  weighted_average_watts?: number | null
  kilojoules?: number | null
  average_cadence?: number | null
  calories?: number | null
  suffer_score?: number | null
  gear_id: string
  commute: boolean
  workout_type?: number | null
  location_city: string
  location_state: string
  location_country: string
  summary_polyline: string
  start_lat?: number | null
  start_lng?: number | null
  description: string
  device_name: string
  embed_token: string
  trainer: boolean
  private: boolean
}

/** GetActivityStreamsRow represents a row returned by GetActivityStreams. */
export interface GetActivityStreamsRow {
  stream_type: string
  data: string
  series_type: string
  original_size: string
  resolution: string
}

/** GetActivityTSSByAthleteRow represents a row returned by GetActivityTSSByAthlete. */
export interface GetActivityTSSByAthleteRow {
  tss: number
}

/** GetActivityTSSRow represents a row returned by GetActivityTSS. */
export interface GetActivityTSSRow {
  tss: number
  normalized_power: number
  intensity_factor: number
}

/** GetActivityZoneDistributionRow represents a row returned by GetActivityZoneDistribution. */
export interface GetActivityZoneDistributionRow {
  activity_id: number
  zone_def_id: string
  seconds_z1: number
  seconds_z2: number
  seconds_z3: number
  seconds_z4: number
  seconds_z5: number
  total_seconds: number
  computed_at: string
}

/** GetAllDailyTSSRow represents a row returned by GetAllDailyTSS. */
export interface GetAllDailyTSSRow {
  day: string
  tss: number
}

/** GetBestEffortPRsBySportRow represents a row returned by GetBestEffortPRsBySport. */
export interface GetBestEffortPRsBySportRow {
  distance_type: number
  name: string
  distance_m: number
  elapsed_time: number
  moving_time: number
  pr_rank?: number | null
  activity_id: number
  activity_name: string
  sport_type: string
  start_date_local: string
}

/** GetBestEffortPRsRow represents a row returned by GetBestEffortPRs. */
export interface GetBestEffortPRsRow {
  distance_type: number
  name: string
  distance_m: number
  elapsed_time: number
  moving_time: number
  pr_rank?: number | null
  activity_id: number
  activity_name: string
  sport_type: string
  start_date_local: string
}

/** GetBestEffortsForDistanceRow represents a row returned by GetBestEffortsForDistance. */
export interface GetBestEffortsForDistanceRow {
  distance_type: number
  name: string
  distance_m: number
  elapsed_time: number
  moving_time: number
  pr_rank?: number | null
  activity_id: number
  activity_name: string
  sport_type: string
  start_date_local: string
  rn: string
}

/** GetCalendarActivitiesRow represents a row returned by GetCalendarActivities. */
export interface GetCalendarActivitiesRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  distance: number
  moving_time: number
  total_elevation_gain: number
}

/** GetCalendarDataRow represents a row returned by GetCalendarData. */
export interface GetCalendarDataRow {
  date: string
  activity_count: number
  total_distance: number
  total_time: number
  total_calories: number
}

/** GetCalendarSummaryRow represents a row returned by GetCalendarSummary. */
export interface GetCalendarSummaryRow {
  activity_count: number
  total_distance: number
  total_elevation: number
  total_time: number
  total_calories: number
  workout_count: number
}

/** GetCustomGearRow represents a row returned by GetCustomGear. */
export interface GetCustomGearRow {
  id: string
  name: string
  is_primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
  source: string
  hashtag: string
  purchase_price?: number | null
  purchase_currency: string
  activity_count: number
}

/** GetDailyTSSRow represents a row returned by GetDailyTSS. */
export interface GetDailyTSSRow {
  day: string
  tss: number
}

/** GetDashboardConfigRow represents a row returned by GetDashboardConfig. */
export interface GetDashboardConfigRow {
  config: string
}

/** GetDashboardStatsFromDateRow represents a row returned by GetDashboardStatsFromDate. */
export interface GetDashboardStatsFromDateRow {
  total_activities: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetDashboardStatsRow represents a row returned by GetDashboardStats. */
export interface GetDashboardStatsRow {
  total_activities: number
  total_distance: number
  total_time: number
  total_elevation: number
  total_calories: number
}

/** GetDaytimeDistributionRow represents a row returned by GetDaytimeDistribution. */
export interface GetDaytimeDistributionRow {
  hour: string
  count: number
}

/** GetEddingtonDaysBySportRow represents a row returned by GetEddingtonDaysBySport. */
export interface GetEddingtonDaysBySportRow {
  date: string
  distance_km: number
}

/** GetEddingtonDaysChronologicalRow represents a row returned by GetEddingtonDaysChronological. */
export interface GetEddingtonDaysChronologicalRow {
  date: string
  distance_km: number
}

/** GetEddingtonDaysRow represents a row returned by GetEddingtonDays. */
export interface GetEddingtonDaysRow {
  date: string
  distance_km: number
}

/** GetGearActivityCountRow represents a row returned by GetGearActivityCount. */
export interface GetGearActivityCountRow {
  count: number
}

/** GetGearByIDRow represents a row returned by GetGearByID. */
export interface GetGearByIDRow {
  id: string
  athlete_id: number
  name: string
  is_primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
  source: string
  hashtag: string
  purchase_price?: number | null
  purchase_currency: string
  created_at: string
  updated_at: string
}

/** GetGearDetailRow represents a row returned by GetGearDetail. */
export interface GetGearDetailRow {
  id: string
  name: string
  is_primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
  source: string
  hashtag: string
  purchase_price?: number | null
  purchase_currency: string
  activity_count: number
}

/** GetGearMonthlyUsageRow represents a row returned by GetGearMonthlyUsage. */
export interface GetGearMonthlyUsageRow {
  gear_id: string
  gear_name: string
  source: string
  hashtag: string
  retired: boolean
  purchase_price?: number | null
  purchase_currency: string
  month: string
  activity_count: number
  distance: number
  moving_time: number
}

/** GetGearRow represents a row returned by GetGear. */
export interface GetGearRow {
  id: string
  athlete_id: number
  name: string
  is_primary: boolean
  retired: boolean
  distance: number
  brand_name: string
  model_name: string
  description: string
  source: string
  hashtag: string
  purchase_price?: number | null
  purchase_currency: string
  created_at: string
  updated_at: string
}

/** GetGearTotalDistanceRow represents a row returned by GetGearTotalDistance. */
export interface GetGearTotalDistanceRow {
  total_distance: number
}

/** GetHeatmapActivitiesByDateRangeRow represents a row returned by GetHeatmapActivitiesByDateRange. */
export interface GetHeatmapActivitiesByDateRangeRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  summary_polyline: string
  start_lat: number
  start_lng: number
}

/** GetHeatmapActivitiesBySportAndDateRangeRow represents a row returned by GetHeatmapActivitiesBySportAndDateRange. */
export interface GetHeatmapActivitiesBySportAndDateRangeRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  summary_polyline: string
  start_lat: number
  start_lng: number
}

/** GetHeatmapActivitiesBySportRow represents a row returned by GetHeatmapActivitiesBySport. */
export interface GetHeatmapActivitiesBySportRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  summary_polyline: string
  start_lat: number
  start_lng: number
}

/** GetHeatmapActivitiesRow represents a row returned by GetHeatmapActivities. */
export interface GetHeatmapActivitiesRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  summary_polyline: string
  start_lat: number
  start_lng: number
}

/** GetHeatmapCountriesRow represents a row returned by GetHeatmapCountries. */
export interface GetHeatmapCountriesRow {
  country: string
  count: number
}

/** GetMonthlyDistributionRow represents a row returned by GetMonthlyDistribution. */
export interface GetMonthlyDistributionRow {
  month: string
  count: number
}

/** GetMonthlyStatsRow represents a row returned by GetMonthlyStats. */
export interface GetMonthlyStatsRow {
  month: string
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetNotifiedKeysByTypesRow represents a row returned by GetNotifiedKeysByTypes. */
export interface GetNotifiedKeysByTypesRow {
  achievement_type: string
  achievement_key: string
}

/** GetNotifiedKeysRow represents a row returned by GetNotifiedKeys. */
export interface GetNotifiedKeysRow {
  achievement_type: string
  achievement_key: string
}

/** GetPowerBestsForDurationsRow represents a row returned by GetPowerBestsForDurations. */
export interface GetPowerBestsForDurationsRow {
  duration_s: string
  watts?: number | null
  activity_id: number
  start_date: string
  activity_name: string
}

/** GetPowerBestsRow represents a row returned by GetPowerBests. */
export interface GetPowerBestsRow {
  duration_s: string
  watts?: number | null
  activity_id: number
  start_date: string
  activity_name: string
}

/** GetPowerHistoryRow represents a row returned by GetPowerHistory. */
export interface GetPowerHistoryRow {
  duration_s: string
  watts?: number | null
  activity_id: number
  start_date: string
  activity_name: string
  rn: string
}

/** GetRecentActivitiesRow represents a row returned by GetRecentActivities. */
export interface GetRecentActivitiesRow {
  id: number
  name: string
  sport_type: string
  start_date: string
  start_date_local: string
  distance: number
  moving_time: number
  total_elevation_gain: number
  average_speed: number
  max_speed: number
}

/** GetSegmentByIDRow represents a row returned by GetSegmentByID. */
export interface GetSegmentByIDRow {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade?: number | null
  maximum_grade?: number | null
  elevation_high: number
  elevation_low: number
  climb_category: number
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  starred: boolean
  polyline: string
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date?: string | null
  created_at: string
  updated_at: string
}

/** GetSegmentCountriesRow represents a row returned by GetSegmentCountries. */
export interface GetSegmentCountriesRow {
  country: string
  segment_count: number
}

/** GetSegmentCountryStatsRow represents a row returned by GetSegmentCountryStats. */
export interface GetSegmentCountryStatsRow {
  country: string
  count: number
}

/** GetSegmentDetailRow represents a row returned by GetSegmentDetail. */
export interface GetSegmentDetailRow {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade?: number | null
  maximum_grade?: number | null
  elevation_high: number
  elevation_low: number
  climb_category: number
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  starred: boolean
  polyline: string
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date?: string | null
}

/** GetSegmentEffortCountriesRow represents a row returned by GetSegmentEffortCountries. */
export interface GetSegmentEffortCountriesRow {
  country: string
}

/** GetSegmentEffortsRow represents a row returned by GetSegmentEfforts. */
export interface GetSegmentEffortsRow {
  id: number
  segment_id: number
  activity_id: number
  athlete_id: number
  name: string
  elapsed_time: number
  moving_time: number
  start_date: string
  start_date_local: string
  distance: number
  average_watts?: number | null
  average_heartrate?: number | null
  max_heartrate?: number | null
  pr_rank?: number | null
}

/** GetSegmentsByCountryRow represents a row returned by GetSegmentsByCountry. */
export interface GetSegmentsByCountryRow {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade?: number | null
  maximum_grade?: number | null
  elevation_high: number
  elevation_low: number
  climb_category: number
  starred: boolean
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date?: string | null
  times_completed: string
  last_effort_date?: string | null
  best_elapsed_time?: number | null
}

/** GetSegmentsRow represents a row returned by GetSegments. */
export interface GetSegmentsRow {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade?: number | null
  maximum_grade?: number | null
  elevation_high: number
  elevation_low: number
  climb_category: number
  starred: boolean
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date?: string | null
  times_completed: string
  last_effort_date?: string | null
  best_elapsed_time?: number | null
}

/** GetSportTypeStatsRow represents a row returned by GetSportTypeStats. */
export interface GetSportTypeStatsRow {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetStatsBySportTypeFromDateRow represents a row returned by GetStatsBySportTypeFromDate. */
export interface GetStatsBySportTypeFromDateRow {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetStatsBySportTypeRow represents a row returned by GetStatsBySportType. */
export interface GetStatsBySportTypeRow {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetTotalZoneDistributionRow represents a row returned by GetTotalZoneDistribution. */
export interface GetTotalZoneDistributionRow {
  z1: number
  z2: number
  z3: number
  z4: number
  z5: number
  total: number
}

/** GetTrainingGoalsConfigRow represents a row returned by GetTrainingGoalsConfig. */
export interface GetTrainingGoalsConfigRow {
  config: string
}

/** GetTrainingLoadSummaryRow represents a row returned by GetTrainingLoadSummary. */
export interface GetTrainingLoadSummaryRow {
  day: string
  tss: number
  ctl: number
  atl: number
  tsb: number
}

/** GetWeekdayDistributionRow represents a row returned by GetWeekdayDistribution. */
export interface GetWeekdayDistributionRow {
  weekday: string
  count: number
}

/** GetWeeklyStatsRow represents a row returned by GetWeeklyStats. */
export interface GetWeeklyStatsRow {
  week: string
  week_start: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** GetWeeklyZoneDistributionRow represents a row returned by GetWeeklyZoneDistribution. */
export interface GetWeeklyZoneDistributionRow {
  week: string
  z1: number
  z2: number
  z3: number
  z4: number
  z5: number
  total: number
}

/** GetYearlyStatsRow represents a row returned by GetYearlyStats. */
export interface GetYearlyStatsRow {
  year: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** HasBeenNotifiedRow represents a row returned by HasBeenNotified. */
export interface HasBeenNotifiedRow {
  count: number
}

// ============================================================================
// From segments.go
// ============================================================================

export interface CountryStat {
  country: string
  count: number
}

/** CountryStats represents segment statistics for a country. */
export interface CountryStats {
  country: string
  iso2?: string
  count: number
}

/** GetSegmentInput contains parameters for getting a single segment. */
export interface GetSegmentInput {
  segment_id: number
}

/** ListEffortsInput contains parameters for listing segment efforts. */
export interface ListEffortsInput {
  segment_id: number
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListEffortsOutput contains a paginated list of segment efforts. */
export interface ListEffortsOutput {
  data: SegmentEffortItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

/** ListSegmentsInput contains parameters for listing segments. */
export interface ListSegmentsInput {
  activity_type: string
  country: string
  search: string
  kom_only: boolean
  starred?: boolean | null
  page: number
  per_page: number
  order_by: string
  order_dir: string
}

/** ListSegmentsOutput contains a paginated list of segments. */
export interface ListSegmentsOutput {
  data: SegmentListItem[]
  total: number
  page: number
  per_page: number
  total_pages: number
}

/** SaveSegmentEffortInput contains parameters for saving a segment effort. */
export interface SaveSegmentEffortInput {
  id: number
  segment_id: number
  activity_id: number
  athlete_id: number
  name: string
  elapsed_time: number
  moving_time: number
  start_date: string
  start_date_local: string
  distance: number
  average_watts?: number | null
  average_heartrate?: number | null
  max_heartrate?: number | null
  pr_rank?: number | null
}

/** SaveSegmentEffortOutput contains the result of saving a segment effort. */
export interface SaveSegmentEffortOutput {
  message: string
}

/** SaveSegmentInput contains parameters for saving a segment. */
export interface SaveSegmentInput {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade: number
  maximum_grade: number
  elevation_high: number
  elevation_low: number
  climb_category: number
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  starred: boolean
  polyline: string
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date: string
}

/** SaveSegmentOutput contains the result of saving a segment. */
export interface SaveSegmentOutput {
  message: string
}

/** SegmentDetailOutput contains a segment with its effort history. */
export interface SegmentDetailOutput {
  segment: SegmentItem
  efforts: SegmentEffortItem[]
}

/** SegmentEffortItem represents a segment effort in responses. */
export interface SegmentEffortItem {
  id: number
  segment_id: number
  activity_id: number
  athlete_id: number
  name?: string
  elapsed_time: number
  moving_time: number
  start_date?: string | null
  start_date_local?: string | null
  distance: number
  average_watts?: number | null
  average_heartrate?: number | null
  max_heartrate?: number | null
  pr_rank?: number | null
  country?: string
}

/** SegmentItem represents a segment in responses. */
export interface SegmentItem {
  id: number
  name: string
  activity_type: string
  distance: number
  average_grade: number
  maximum_grade: number
  elevation_high: number
  elevation_low: number
  climb_category: number
  start_lat?: number | null
  start_lng?: number | null
  end_lat?: number | null
  end_lng?: number | null
  starred: boolean
  polyline?: string
  athlete_kom_rank?: number | null
  athlete_effort_count?: number | null
  athlete_pr_elapsed_time?: number | null
  athlete_pr_date?: string | null
}

/** SegmentListItem represents a segment in list responses with effort statistics. */
export interface SegmentListItem {
  times_completed: number
  last_effort_date?: string | null
  best_elapsed_time?: number | null
}

// ============================================================================
// From settings.go
// ============================================================================

export interface AthleteSettings {
  version: number
  virtual_world_tile_layers: Record<string, VirtualWorldTileLayer>
  eddington_definitions?: EddingtonDefinition[]
  scheduler: SchedulerSettings
  enable_public_badges: boolean
  notifications?: NotificationConfig | null
}

export interface EddingtonDefinition {
  id: string
  name: string
  sport_types?: string[]
  show_in_nav?: boolean
  show_in_dashboard_widget?: boolean
}

export interface PullSettings {
  enabled: boolean
  schedule: string
}

export interface PushSettings {
  enabled: boolean
}

export interface SchedulerSettings {
  version: number
  pull: PullSettings
  push: PushSettings
}

export interface VirtualWorldTileLayer {
  name: string
  url: string
  attribution?: string
  max_zoom?: number
}

// ============================================================================
// From setup.go
// ============================================================================

/** CredentialsStatusResponse represents the credentials status response. */
export interface CredentialsStatusResponse {
  configured: boolean
  client_id?: string
  source?: string
  redirect_uri: string
}

/** UpdateCredentialsRequest represents the request to update credentials. */
export interface UpdateCredentialsRequest {
  client_id: string
  client_secret: string
}

// ============================================================================
// From stats.go
// ============================================================================

/** BestEffortListItem represents a best effort item in a list. */
export interface BestEffortListItem {
  distance_type: string
  name: string
  distance_m: number
  elapsed_time_s: number
  moving_time_s?: number | null
  pr_rank?: number | null
  start_index?: number | null
  end_index?: number | null
  activity_id: number
  activity_name: string
  sport_type: string
  start_date_local: string
}

/** BestEffortPR represents a personal record for a distance type. */
export interface BestEffortPR {
  distance_type: string
  name: string
  distance_m: number
  elapsed_time_s: number
  moving_time_s?: number | null
  pr_rank?: number | null
  activity_id: number
  activity_name: string
  sport_type: string
  start_date_local: string
}

/** CalendarActivity represents an activity summary for the calendar view. */
export interface CalendarActivity {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  moving_time: number
  total_elevation_gain: number
}

/** CalendarDay represents activity data for a single day. */
export interface CalendarDay {
  date: string
  activity_count: number
  total_distance: number
  total_time: number
  total_calories: number
}

export interface CalendarMonthSummary {
  year: number
  month: number
  activity_count: number
  total_distance: number
  total_elevation_gain: number
  total_moving_time: number
  total_calories: number
  workout_count: number
  challenges_completed: number
}

export interface ComputePowerBestEffortsInput {
  activity_id: number
  athlete_id: number
}

/** DailyTrainingLoadPoint represents training load for a single day. */
export interface DailyTrainingLoadPoint {
  day: string
  tss: number
  ctl: number
  atl: number
  tsb: number
}

/** DashboardStats represents aggregated statistics for the dashboard. */
export interface DashboardStats {
  total_activities: number
  total_distance: number
  total_moving_time: number
  total_elevation_gain: number
  total_calories: number
  year_activities: number
  year_distance: number
  year_moving_time: number
  year_elevation_gain: number
  month_activities: number
  month_distance: number
  month_moving_time: number
  month_elevation_gain: number
}

/** DigestStats represents aggregated statistics for digest notifications. */
export interface DigestStats {
  start_date: string
  end_date: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
  total_calories: number
}

export interface DistributionSlice {
  label: string
  count: number
}

/** EddingtonDay represents a day's distance for Eddington calculation. */
export interface EddingtonDay {
  date: string
  distance: number
}

/** EddingtonHistoryPoint represents a milestone point where the Eddington number increases. */
export interface EddingtonHistoryPoint {
  date: string
  number: number
}

/** EddingtonOutput contains the Eddington number calculation result. */
export interface EddingtonOutput {
  number: number
  distribution: EddingtonDay[]
  next_steps: EddingtonStep[]
}

/** EddingtonResult contains the Eddington number calculation result. */
export interface EddingtonResult {
  number: number
  distribution: EddingtonDay[]
  next_steps: EddingtonStep[]
}

/** EddingtonStep shows how many rides needed to reach the next Eddington number. */
export interface EddingtonStep {
  target: number
  rides_needed: number
}

/** GetBestEffortPRsInput contains parameters for getting best effort PRs. */
export interface GetBestEffortPRsInput {
  sport_types: string[]
}

/** GetBestEffortsForTypeInput contains parameters for getting best efforts by distance type. */
export interface GetBestEffortsForTypeInput {
  distance_type: string
  sport_types: string[]
}

/** GetEddingtonDataInput contains parameters for getting Eddington data. */
export interface GetEddingtonDataInput {
  sport_types: string[]
}

/** GetEddingtonHistoryInput contains parameters for getting Eddington history. */
export interface GetEddingtonHistoryInput {
  sport_types: string[]
}

/** GetHeatmapDataInput contains parameters for getting heatmap data. */
export interface GetHeatmapDataInput {
  sport_types: string[]
  after?: string | null
  before?: string | null
  commute?: boolean | null
  workout_type?: number | null
  limit: number
  offset: number
}

/** GetPowerStatsInput contains parameters for getting power stats. */
export interface GetPowerStatsInput {
  after?: string | null
  before?: string | null
  sport_types: string[]
}

/** GetTrainingLoadInput contains parameters for getting training load data. */
export interface GetTrainingLoadInput {
  after?: string | null
  before?: string | null
}

/** GetWrappedInput contains parameters for getting wrapped data. */
export interface GetWrappedInput {
  year: number
}

/** GetZoneTrendInput contains parameters for getting zone trend data. */
export interface GetZoneTrendInput {
  weeks: number
}

export interface HRZonesResponse {
  method: string
  zones: HRZoneConfig
  seconds_by_zone: number[]
  total_seconds: number
}

/** HeatmapActivity represents an activity for the heatmap visualization. */
export interface HeatmapActivity {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  summary_polyline: string
  start_lat: number
  start_lng: number
}

/** HeatmapCountryStat represents country statistics for heatmap. */
export interface HeatmapCountryStat {
  country: string
  iso2?: string
  count: number
}

/** HeatmapOutput contains the heatmap data and summary statistics. */
export interface HeatmapOutput {
  activities: HeatmapActivity[]
  total: number
  limit?: number
  offset?: number
  countries?: HeatmapCountryStat[]
}

/** MonthlyStat represents statistics for a single month. */
export interface MonthlyStat {
  month: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** PeakPowerBest represents the best power for a duration. */
export interface PeakPowerBest {
  duration_s: number
  watts: number
  activity_id: number
  start_date: string
}

/** PeakPowerHistoryPoint represents a point in power history. */
export interface PeakPowerHistoryPoint {
  date: string
  watts: number
}

/** PowerStatsOutput contains power statistics. */
export interface PowerStatsOutput {
  durations_s: number[]
  best: PeakPowerBest[]
  history: Record<number, PeakPowerHistoryPoint[]>
}

export interface PowerZonesResponse {
  ftp_watts?: number
  seconds_by_zone: number[]
  total_seconds: number
  bounds: number[]
}

/** RecentActivity represents a simplified activity for the dashboard. */
export interface RecentActivity {
  id: number
  name: string
  sport_type: string
  start_date: string
  distance: number
  moving_time: number
  elevation_gain: number
  summary_polyline?: string
}

/** SaveBestEffortsInput contains parameters for saving best efforts for an activity. */
export interface SaveBestEffortsInput {
  athlete_id: number
  activity_id: number
  sport_type: string
  efforts: SaveBestEffortsInputItem[]
}

/** SaveBestEffortsInputItem represents a single best effort to save. */
export interface SaveBestEffortsInputItem {
  distance_type: string
  name: string
  distance_m: number
  elapsed_time: number
  moving_time?: number | null
  start_index?: number | null
  end_index?: number | null
  pr_rank?: number | null
  start_date: string
}

/** SaveBestEffortsOutput contains the result of saving best efforts. */
export interface SaveBestEffortsOutput {
  message: string
}

/** SportTypeStat represents statistics for a single sport type. */
export interface SportTypeStat {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** TrainingLoadOutput contains training load data. */
export interface TrainingLoadOutput {
  series: DailyTrainingLoadPoint[]
  summary?: DailyTrainingLoadPoint | null
}

/** WeeklyStat represents statistics for a single sport type in the current week. */
export interface WeeklyStat {
  sport_type: string
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** WeeklyZoneDistribution represents zone data for a single week. */
export interface WeeklyZoneDistribution {
  week: string
  seconds_z1: number
  seconds_z2: number
  seconds_z3: number
  seconds_z4: number
  seconds_z5: number
  total: number
  percent_z1: number
  percent_z2: number
  percent_z3: number
  percent_z4: number
  percent_z5: number
}

/** WrappedBiggest contains the biggest activities. */
export interface WrappedBiggest {
  longest_distance?: WrappedBiggestActivity | null
  most_elevation?: WrappedBiggestActivity | null
  longest_duration?: WrappedBiggestActivity | null
}

/** WrappedBiggestActivity represents the biggest activity for a metric. */
export interface WrappedBiggestActivity {
  activity_id: number
  name: string
  sport_type: string
  start_date_local: string
  value: number
}

/** WrappedHourCount represents activity count by hour. */
export interface WrappedHourCount {
  hour: number
  count: number
}

/** WrappedLocationPoint represents a location bucket. */
export interface WrappedLocationPoint {
  lat: number
  lng: number
  count: number
}

/** WrappedMonth represents monthly statistics for wrapped. */
export interface WrappedMonth {
  month: string
  activities: number
  distance_m: number
  elevation_m: number
  prs: number
}

/** WrappedOutput contains the wrapped report. */
export interface WrappedOutput {
  year: number
  range_start: string
  range_end: string
  total_days: number
  active_days: number
  rest_days: number
  totals: WrappedTotals
  months?: WrappedMonth[]
  moving_time_by_sport: WrappedSportTime[]
  start_times_by_hour: WrappedHourCount[]
  locations: WrappedLocationPoint[]
  streaks: WrappedStreaks
  random_photo?: WrappedPhoto | null
  biggest: WrappedBiggest
}

/** WrappedPhoto represents a photo in the wrapped. */
export interface WrappedPhoto {
  id: string
  activity_id: number
  url: string
  thumbnail_url?: string
  caption?: string
}

/** WrappedSportTime represents moving time by sport type. */
export interface WrappedSportTime {
  sport_type: string
  moving_time_s: number
}

/** WrappedStreaks represents streak data. */
export interface WrappedStreaks {
  longest_active_days: number
  longest_rest_days: number
}

/** WrappedTotals represents totals for the wrapped report. */
export interface WrappedTotals {
  activities: number
  distance_m: number
  elevation_m: number
  moving_time_s: number
  kudos: number
  commute_distance_m: number
  carbon_saved_kg: number
}

/** YearStat represents statistics for a single year. */
export interface YearStat {
  year: number
  activity_count: number
  total_distance: number
  total_time: number
  total_elevation: number
}

/** ZoneTrendOutput contains zone trend data. */
export interface ZoneTrendOutput {
  weeks: WeeklyZoneDistribution[]
}

// ============================================================================
// From sync.go
// ============================================================================

export interface CompleteSyncRunRequest {
  id: number
  status: string
  error: string
  activities_total: number
  activities_imported: number
  activities_skipped: number
  gear_imported: number
  streams_imported: number
  segments_imported: number
  photos_imported: number
  failed_count: number
  newest_activity_date: string
}

export interface CreateSyncRunInput {
  athlete_id: number
  full_sync: boolean
  skip_streams: boolean
  skip_segments: boolean
  skip_best_efforts: boolean
  skip_photos: boolean
}

export interface UpdateSyncRunInput {
  id: number
  status: string
  activities_total: number
  activities_imported: number
  streams_imported: number
  failed_count: number
  newest_activity_date: string
}

// ============================================================================
// From sync_history.go
// ============================================================================

/** SyncRun represents a single import/sync run. */
export interface SyncRun {
  id: number
  athlete_id: number
  started_at: string
  completed_at?: string | null
  duration_seconds?: number | null
  status: string
  error?: string
  activities_total: number
  activities_imported: number
  activities_skipped: number
  gear_imported: number
  streams_imported: number
  segments_imported: number
  photos_imported: number
  failed_count: number
  full_sync: boolean
  skip_streams: boolean
  skip_segments: boolean
  skip_best_efforts: boolean
  skip_photos: boolean
  newest_activity_date?: string | null
  created_at: string
}

/** SyncWatermark stores the sync watermark for incremental syncs. */
export interface SyncWatermark {
  last_synced_at: string
  newest_activity_date?: string | null
}

// ============================================================================
// From types.go
// ============================================================================

/** EventConfig defines which events trigger notifications. */
export interface EventConfig {
  importComplete: boolean
  maintenanceDue: boolean
  maintenanceSchedule: string
  personalRecords: boolean
  segmentPRs: boolean
  eddingtonIncrease: boolean
  powerRecords: boolean
  goalComplete: boolean
  fatigueWarning: boolean
  recoveryAlert: boolean
  overtrainingRisk: boolean
  weeklyDigest: boolean
  monthlyDigest: boolean
  gearMilestones: boolean
}

/** NotificationConfig holds the notification configuration for an athlete. */
export interface NotificationConfig {
  enabled: boolean
  services: ServiceConfig[]
  events: EventConfig
}

/** ServiceConfig defines a notification service configuration. */
export interface ServiceConfig {
  id: string
  type: string
  name: string
  enabled: boolean
  config: Record<string, string>
}

// ============================================================================
// From webhooks.go
// ============================================================================

export interface StravaWebhookEvent {
  object_type: string
  object_id: number
  aspect_type: string
  owner_id: number
  subscription_id: number
  event_time: number
  updates?: Record<string, unknown>
}

/** StravaWebhookValidationResponse matches Strava's expected response body: */
export interface StravaWebhookValidationResponse {
  'hub.challenge': string
}

// ============================================================================
// From wrapped.go
// ============================================================================

export interface WrappedReport {
  year: number
  range_start: string
  range_end: string
  total_days: number
  active_days: number
  rest_days: number
  totals: WrappedTotals
  months?: WrappedMonth[]
  moving_time_by_sport: WrappedSportTime[]
  start_times_by_hour: WrappedHourCount[]
  locations: WrappedLocationPoint[]
  streaks: WrappedStreaks
  random_photo?: WrappedPhoto | null
  biggest: WrappedBiggest
}

// ============================================================================
// From zone_distribution.go
// ============================================================================

/** ActivityZoneDistribution stores the time spent in each HR zone for an activity. */
export interface ActivityZoneDistribution {
  activity_id: number
  zone_def_id: string
  seconds_z1: number
  seconds_z2: number
  seconds_z3: number
  seconds_z4: number
  seconds_z5: number
  total_seconds: number
  computed_at: string
}

/** TotalZoneDistribution represents aggregated zone data across all activities. */
export interface TotalZoneDistribution {
  seconds_z1: number
  seconds_z2: number
  seconds_z3: number
  seconds_z4: number
  seconds_z5: number
  total_seconds: number
}

// ============================================================================
// From zones.go
// ============================================================================

export interface HRZoneConfig {
  bounds: number[]
  hr_max?: number
}

export interface HRZoneDefinition {
  sport_type: string
  effective_from: string
  method: string
  zones: unknown
}

