// Code generated by scripts/generate-schema. DO NOT EDIT.

/**
 * Database migrations for browser WASM mode.
 * These are embedded at build time from schema/migrations/*.sql
 *
 * @deprecated Migrations are now handled exclusively by Go WASM (storage.RunMigrations).
 * This file is generated for reference only and is no longer used at runtime.
 * The Go WASM layer uses the _migrations table for tracking, not schema_version.
 */

export interface Migration {
  version: number
  name: string
  sql: string
}

export const migrations: Migration[] = [
  {
    version: 1,
    name: "initial",
    sql: `-- Quantlete: Complete SQLite Schema
-- Consolidated schema with all tables, views, and indexes

PRAGMA foreign_keys = ON;

--------------------------------------------------------------------------------
-- Athletes & Authentication
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS athletes (
    id INTEGER PRIMARY KEY,
    username TEXT,
    firstname TEXT,
    lastname TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    sex TEXT,
    premium INTEGER DEFAULT 0,
    summit INTEGER DEFAULT 0,
    profile_medium TEXT,
    profile TEXT,
    weight REAL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_tokens (
    athlete_id INTEGER PRIMARY KEY REFERENCES athletes(id),
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    token_type TEXT DEFAULT 'Bearer',
    expires_at TEXT NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON auth_tokens(expires_at);

--------------------------------------------------------------------------------
-- Activities
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activities (
    id INTEGER PRIMARY KEY,
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    name TEXT NOT NULL,
    description TEXT,
    sport_type TEXT NOT NULL,
    start_date TEXT NOT NULL,
    start_date_local TEXT NOT NULL,
    timezone TEXT,

    -- Location
    location_city TEXT,
    location_state TEXT,
    location_country TEXT,

    -- Metrics
    distance REAL DEFAULT 0,
    moving_time INTEGER DEFAULT 0,
    elapsed_time INTEGER DEFAULT 0,
    total_elevation_gain REAL DEFAULT 0,
    elev_high REAL,
    elev_low REAL,

    -- Speed
    average_speed REAL DEFAULT 0,
    max_speed REAL DEFAULT 0,

    -- Heart rate
    average_heartrate REAL,
    max_heartrate INTEGER,

    -- Power
    average_watts REAL,
    max_watts INTEGER,
    weighted_average_watts INTEGER,
    kilojoules REAL,

    -- Cadence
    average_cadence REAL,

    -- Other
    calories REAL,
    suffer_score INTEGER,
    kudos_count INTEGER DEFAULT 0,
    comment_count INTEGER DEFAULT 0,
    photo_count INTEGER DEFAULT 0,
    commute INTEGER DEFAULT 0,
    private INTEGER DEFAULT 0,
    trainer INTEGER DEFAULT 0,
    workout_type INTEGER,
    device_name TEXT,
    gear_id TEXT,
    embed_token TEXT,

    -- Coordinates
    start_lat REAL,
    start_lng REAL,
    end_lat REAL,
    end_lng REAL,

    -- Map data
    polyline TEXT,
    summary_polyline TEXT,

    -- Metadata
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activities_athlete_id ON activities(athlete_id);
CREATE INDEX IF NOT EXISTS idx_activities_sport_type ON activities(sport_type);
CREATE INDEX IF NOT EXISTS idx_activities_start_date ON activities(start_date DESC);
CREATE INDEX IF NOT EXISTS idx_activities_gear_id ON activities(gear_id);
CREATE INDEX IF NOT EXISTS idx_activities_commute ON activities(commute);
CREATE INDEX IF NOT EXISTS idx_activities_location_country ON activities(location_country);
CREATE INDEX IF NOT EXISTS idx_activities_athlete_sport_date ON activities(athlete_id, sport_type, start_date DESC);
CREATE INDEX IF NOT EXISTS idx_activities_athlete_gear ON activities(athlete_id, gear_id);
CREATE INDEX IF NOT EXISTS idx_activities_athlete_commute ON activities(athlete_id, commute);
CREATE INDEX IF NOT EXISTS idx_activities_athlete_trainer ON activities(athlete_id, trainer);

--------------------------------------------------------------------------------
-- Activity Streams
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_streams (
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    stream_type TEXT NOT NULL,
    original_size INTEGER,
    resolution TEXT,
    series_type TEXT,
    data BLOB,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (activity_id, stream_type)
);

CREATE INDEX IF NOT EXISTS idx_streams_activity_id ON activity_streams(activity_id);

--------------------------------------------------------------------------------
-- Gear & Maintenance
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS gear (
    id TEXT PRIMARY KEY,
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    name TEXT NOT NULL,
    is_primary INTEGER DEFAULT 0,
    retired INTEGER DEFAULT 0,
    distance REAL DEFAULT 0,
    brand_name TEXT,
    model_name TEXT,
    description TEXT,
    source TEXT DEFAULT 'strava',
    hashtag TEXT,
    purchase_price REAL,
    purchase_currency TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_gear_athlete_id ON gear(athlete_id);
CREATE INDEX IF NOT EXISTS idx_gear_retired ON gear(retired);
CREATE INDEX IF NOT EXISTS idx_gear_source ON gear(source);
CREATE INDEX IF NOT EXISTS idx_gear_hashtag ON gear(hashtag);

CREATE TABLE IF NOT EXISTS components (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    gear_id TEXT NOT NULL REFERENCES gear(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    maintenance_hashtag TEXT,
    installed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    retired_at DATETIME,
    initial_distance REAL DEFAULT 0,
    initial_time INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_components_gear_id ON components(gear_id);
CREATE INDEX IF NOT EXISTS idx_components_gear_created ON components(gear_id, created_at ASC);

CREATE TABLE IF NOT EXISTS maintenance_rules (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    component_id INTEGER NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    metric TEXT NOT NULL CHECK(metric IN ('distance', 'time', 'interval')),
    type TEXT,
    threshold_value REAL NOT NULL,
    threshold_unit TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_maintenance_rules_component_id ON maintenance_rules(component_id);

CREATE TABLE IF NOT EXISTS maintenance_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    component_id INTEGER NOT NULL REFERENCES components(id) ON DELETE CASCADE,
    activity_id INTEGER REFERENCES activities(id) ON DELETE SET NULL,
    completed_at DATETIME NOT NULL,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_maintenance_log_component_id ON maintenance_log(component_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_log_activity_id ON maintenance_log(activity_id);

--------------------------------------------------------------------------------
-- Segments
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS segments (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    activity_type TEXT,
    distance REAL,
    average_grade REAL,
    maximum_grade REAL,
    elevation_high REAL,
    elevation_low REAL,
    climb_category INTEGER,
    start_lat REAL,
    start_lng REAL,
    end_lat REAL,
    end_lng REAL,
    starred INTEGER DEFAULT 0,
    polyline TEXT,
    athlete_kom_rank INTEGER,
    athlete_effort_count INTEGER,
    athlete_pr_elapsed_time INTEGER,
    athlete_pr_date TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS segment_efforts (
    id INTEGER PRIMARY KEY,
    segment_id INTEGER NOT NULL REFERENCES segments(id) ON DELETE CASCADE,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    athlete_id INTEGER NOT NULL,
    name TEXT,
    elapsed_time INTEGER,
    moving_time INTEGER,
    start_date DATETIME,
    start_date_local DATETIME,
    distance REAL,
    average_watts REAL,
    average_heartrate REAL,
    max_heartrate INTEGER,
    pr_rank INTEGER,
    country TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_segment_efforts_segment_id ON segment_efforts(segment_id);
CREATE INDEX IF NOT EXISTS idx_segment_efforts_activity_id ON segment_efforts(activity_id);
CREATE INDEX IF NOT EXISTS idx_segment_efforts_athlete_id ON segment_efforts(athlete_id);
CREATE INDEX IF NOT EXISTS idx_segment_efforts_pr_rank ON segment_efforts(pr_rank);
CREATE INDEX IF NOT EXISTS idx_segment_efforts_country ON segment_efforts(country);
CREATE INDEX IF NOT EXISTS idx_segment_efforts_athlete_country ON segment_efforts(athlete_id, country);

--------------------------------------------------------------------------------
-- Photos
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS photos (
    id TEXT PRIMARY KEY,
    athlete_id INTEGER NOT NULL,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    caption TEXT,
    location BLOB,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_photos_activity_id ON photos(activity_id);
CREATE INDEX IF NOT EXISTS idx_photos_athlete_id ON photos(athlete_id);
CREATE INDEX IF NOT EXISTS idx_photos_athlete_activity ON photos(athlete_id, activity_id);

--------------------------------------------------------------------------------
-- Challenges
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS challenges (
    id TEXT PRIMARY KEY,
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    name TEXT NOT NULL,
    slug TEXT,
    badge_url TEXT,
    local_badge_url TEXT,
    completion_date TEXT,
    month TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_challenges_athlete_id ON challenges(athlete_id);
CREATE INDEX IF NOT EXISTS idx_challenges_month ON challenges(month);
CREATE INDEX IF NOT EXISTS idx_challenges_athlete_completion ON challenges(athlete_id, completion_date);

--------------------------------------------------------------------------------
-- Best Efforts
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS best_efforts (
    athlete_id INTEGER NOT NULL,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE CASCADE,
    sport_type TEXT NOT NULL,
    distance_type TEXT NOT NULL,
    name TEXT NOT NULL,
    distance_m REAL NOT NULL,
    elapsed_time INTEGER NOT NULL,
    moving_time INTEGER,
    start_index INTEGER,
    end_index INTEGER,
    pr_rank INTEGER,
    start_date DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (athlete_id, activity_id, distance_type)
);

CREATE INDEX IF NOT EXISTS idx_best_efforts_athlete_sport_distance ON best_efforts(athlete_id, sport_type, distance_type);

--------------------------------------------------------------------------------
-- Configuration & Settings
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dashboard_config (
    athlete_id INTEGER PRIMARY KEY REFERENCES athletes(id),
    config TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS training_goals (
    athlete_id INTEGER PRIMARY KEY REFERENCES athletes(id),
    config TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS athlete_settings (
    athlete_id INTEGER PRIMARY KEY REFERENCES athletes(id),
    settings TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------------------------------
-- Training Load (TSS/CTL/ATL/TSB)
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_training_load (
    activity_id INTEGER PRIMARY KEY REFERENCES activities(id),
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    sport_type TEXT,
    method TEXT,
    ftp_used REAL,
    normalized_power REAL,
    intensity_factor REAL,
    tss REAL,
    computed_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_training_load (
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    day TEXT NOT NULL,
    tss REAL NOT NULL,
    ctl REAL NOT NULL,
    atl REAL NOT NULL,
    tsb REAL NOT NULL,
    PRIMARY KEY (athlete_id, day)
);

CREATE INDEX IF NOT EXISTS idx_daily_training_load_athlete_day ON daily_training_load(athlete_id, day);

--------------------------------------------------------------------------------
-- Athlete Metrics (FTP, Weight history)
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS athlete_metrics (
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    metric TEXT NOT NULL,
    value REAL NOT NULL,
    recorded_at TEXT NOT NULL,
    PRIMARY KEY (athlete_id, metric, recorded_at)
);

CREATE INDEX IF NOT EXISTS idx_athlete_metrics_athlete_metric ON athlete_metrics(athlete_id, metric);
CREATE INDEX IF NOT EXISTS idx_athlete_metrics_recorded_at ON athlete_metrics(recorded_at);

--------------------------------------------------------------------------------
-- HR Zone Definitions
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hr_zone_definitions (
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    sport_type TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    method TEXT NOT NULL,
    zones TEXT NOT NULL,
    PRIMARY KEY (athlete_id, sport_type, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_hr_zones_athlete_sport ON hr_zone_definitions(athlete_id, sport_type);

--------------------------------------------------------------------------------
-- Power Best Efforts
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS power_best_efforts (
    activity_id INTEGER NOT NULL REFERENCES activities(id),
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),
    duration_s INTEGER NOT NULL,
    best_avg_watts REAL NOT NULL,
    computed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (activity_id, duration_s)
);

CREATE INDEX IF NOT EXISTS idx_power_best_efforts_athlete_duration ON power_best_efforts(athlete_id, duration_s);

--------------------------------------------------------------------------------
-- App State
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS app_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------------------------------
-- Sync History
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sync_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    athlete_id INTEGER NOT NULL REFERENCES athletes(id),

    -- Timing
    started_at TEXT NOT NULL,
    completed_at TEXT,
    duration_seconds INTEGER,

    -- Status
    status TEXT NOT NULL DEFAULT 'running',
    error TEXT,

    -- Counts
    activities_total INTEGER DEFAULT 0,
    activities_imported INTEGER DEFAULT 0,
    activities_skipped INTEGER DEFAULT 0,
    gear_imported INTEGER DEFAULT 0,
    streams_imported INTEGER DEFAULT 0,
    segments_imported INTEGER DEFAULT 0,
    photos_imported INTEGER DEFAULT 0,
    failed_count INTEGER DEFAULT 0,

    -- Options used
    full_sync INTEGER DEFAULT 0,
    skip_streams INTEGER DEFAULT 0,
    skip_segments INTEGER DEFAULT 0,
    skip_best_efforts INTEGER DEFAULT 0,
    skip_photos INTEGER DEFAULT 0,

    -- Watermark: newest activity date synced in this run
    newest_activity_date TEXT,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sync_history_athlete_id ON sync_history(athlete_id);
CREATE INDEX IF NOT EXISTS idx_sync_history_started_at ON sync_history(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_history_status ON sync_history(status);

--------------------------------------------------------------------------------
-- Analytics VIEWs
--------------------------------------------------------------------------------

-- Daily distance aggregation for Eddington number calculation
CREATE VIEW IF NOT EXISTS v_daily_distances AS
SELECT
    athlete_id,
    DATE(start_date) AS date,
    SUM(distance) / 1000.0 AS distance_km
FROM activities
GROUP BY athlete_id, DATE(start_date);

-- Best effort rankings per distance type
CREATE VIEW IF NOT EXISTS v_best_effort_rankings AS
SELECT
    be.athlete_id,
    be.distance_type,
    COALESCE(be.name, be.distance_type) AS name,
    be.distance_m,
    be.elapsed_time,
    be.moving_time,
    be.pr_rank,
    a.id AS activity_id,
    a.name AS activity_name,
    a.sport_type,
    a.start_date_local,
    ROW_NUMBER() OVER (
        PARTITION BY be.athlete_id, be.distance_type
        ORDER BY be.elapsed_time ASC, a.start_date_local ASC
    ) AS rn
FROM best_efforts be
JOIN activities a ON a.id = be.activity_id AND a.athlete_id = be.athlete_id;

-- Peak power rankings per duration
CREATE VIEW IF NOT EXISTS v_power_best_rankings AS
SELECT
    p.athlete_id,
    p.duration_s,
    p.best_avg_watts,
    p.activity_id,
    a.start_date,
    a.name AS activity_name,
    ROW_NUMBER() OVER (
        PARTITION BY p.athlete_id, p.duration_s
        ORDER BY p.best_avg_watts DESC
    ) AS rn
FROM power_best_efforts p
JOIN activities a ON a.id = p.activity_id;

-- Segment statistics with effort counts
CREATE VIEW IF NOT EXISTS v_segment_stats AS
SELECT
    s.id,
    s.name,
    s.activity_type,
    s.distance,
    s.average_grade,
    s.maximum_grade,
    s.elevation_high,
    s.elevation_low,
    s.climb_category,
    s.start_lat,
    s.start_lng,
    s.end_lat,
    s.end_lng,
    s.starred,
    s.polyline,
    s.athlete_kom_rank,
    s.athlete_effort_count,
    s.athlete_pr_elapsed_time,
    s.athlete_pr_date,
    e.athlete_id,
    COUNT(e.id) AS times_completed,
    MAX(e.start_date) AS last_effort_date,
    MIN(NULLIF(e.elapsed_time, 0)) AS best_elapsed_time
FROM segments s
LEFT JOIN segment_efforts e ON e.segment_id = s.id
GROUP BY s.id, e.athlete_id;

-- Monthly activity aggregation by sport type
CREATE VIEW IF NOT EXISTS v_monthly_stats AS
SELECT
    athlete_id,
    strftime('%Y-%m', start_date) AS month,
    sport_type,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y-%m', start_date), sport_type;

-- Yearly activity aggregation
CREATE VIEW IF NOT EXISTS v_yearly_stats AS
SELECT
    athlete_id,
    CAST(strftime('%Y', start_date) AS INTEGER) AS year,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y', start_date);

-- Daily TSS aggregation for training load calculations
CREATE VIEW IF NOT EXISTS v_daily_tss AS
SELECT
    a.athlete_id,
    DATE(a.start_date_local) AS day,
    COALESCE(SUM(tl.tss), 0) AS tss
FROM activities a
LEFT JOIN activity_training_load tl ON tl.activity_id = a.id
GROUP BY a.athlete_id, DATE(a.start_date_local);

-- Weekly activity aggregation
CREATE VIEW IF NOT EXISTS v_weekly_stats AS
SELECT
    athlete_id,
    strftime('%Y-W%W', start_date) AS week,
    strftime('%Y-%m-%d', start_date, 'weekday 0', '-6 days') AS week_start,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y-W%W', start_date);

-- Sport type statistics
CREATE VIEW IF NOT EXISTS v_sport_type_stats AS
SELECT
    athlete_id,
    sport_type,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, sport_type;

-- Gear usage statistics
CREATE VIEW IF NOT EXISTS v_gear_monthly_usage AS
SELECT
    g.id AS gear_id,
    g.name AS gear_name,
    g.source,
    g.hashtag,
    g.retired,
    g.purchase_price,
    g.purchase_currency,
    g.athlete_id,
    strftime('%Y-%m', a.start_date) AS month,
    COUNT(*) AS activity_count,
    COALESCE(SUM(a.distance), 0) AS distance,
    COALESCE(SUM(a.moving_time), 0) AS moving_time
FROM gear g
LEFT JOIN activities a ON a.gear_id = g.id AND a.athlete_id = g.athlete_id
GROUP BY g.id, strftime('%Y-%m', a.start_date);

-- Segment country statistics
CREATE VIEW IF NOT EXISTS v_segment_countries AS
SELECT
    athlete_id,
    country,
    COUNT(DISTINCT segment_id) AS segment_count
FROM segment_efforts
WHERE country IS NOT NULL AND country != ''
GROUP BY athlete_id, country;

-- Heatmap activity data
CREATE VIEW IF NOT EXISTS v_heatmap_activities AS
SELECT
    id,
    athlete_id,
    sport_type,
    summary_polyline,
    COALESCE(start_lat, 0) AS start_lat,
    COALESCE(start_lng, 0) AS start_lng,
    start_date,
    commute,
    workout_type,
    location_country
FROM activities
WHERE summary_polyline IS NOT NULL AND summary_polyline != '';

-- Calendar day statistics
CREATE VIEW IF NOT EXISTS v_calendar_days AS
SELECT
    athlete_id,
    DATE(start_date) AS date,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(calories), 0) AS total_calories
FROM activities
GROUP BY athlete_id, DATE(start_date);

--------------------------------------------------------------------------------
-- Activity Weather
--------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_weather (
    activity_id INTEGER PRIMARY KEY REFERENCES activities(id) ON DELETE CASCADE,
    source TEXT NOT NULL,  -- 'strava' for temp stream, 'open-meteo' for fallback

    -- Current conditions at activity start
    temperature_c REAL,
    feels_like_c REAL,
    humidity_percent REAL,
    wind_speed_mps REAL,
    wind_direction_deg REAL,
    precipitation_mm REAL,
    weather_code INTEGER,  -- WMO weather interpretation codes

    -- Temperature range from Strava stream or Open-Meteo
    temp_min_c REAL,
    temp_max_c REAL,
    temp_avg_c REAL,

    -- Raw temperature stream data (JSON array, only for Strava source)
    temp_stream TEXT,

    -- Metadata
    fetched_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activity_weather_source ON activity_weather(source);

--------------------------------------------------------------------------------
-- Additional Pagination Indexes
--------------------------------------------------------------------------------

-- Segment efforts: composite index for paginated queries
CREATE INDEX IF NOT EXISTS idx_segment_efforts_athlete_segment_date
    ON segment_efforts(athlete_id, segment_id, start_date DESC);

-- Challenges: composite index for sorted pagination
CREATE INDEX IF NOT EXISTS idx_challenges_athlete_month_date
    ON challenges(athlete_id, month DESC, completion_date DESC);

-- Gear: composite index for sorted pagination
CREATE INDEX IF NOT EXISTS idx_gear_athlete_distance
    ON gear(athlete_id, distance DESC);

-- Gear: index for custom gear filtering
CREATE INDEX IF NOT EXISTS idx_gear_athlete_source
    ON gear(athlete_id, source);
`,
  },
  {
    version: 2,
    name: "fix_timezone_views",
    sql: `-- Fix timezone handling: use start_date_local for activity grouping
-- This ensures activities are grouped by their local calendar date, not UTC

-- Drop existing views that use start_date (UTC)
DROP VIEW IF EXISTS v_daily_distances;
DROP VIEW IF EXISTS v_monthly_stats;
DROP VIEW IF EXISTS v_yearly_stats;
DROP VIEW IF EXISTS v_weekly_stats;
DROP VIEW IF EXISTS v_gear_monthly_usage;
DROP VIEW IF EXISTS v_calendar_days;

-- Recreate views with start_date_local for correct timezone grouping

-- Daily distance aggregation for Eddington number calculation
CREATE VIEW v_daily_distances AS
SELECT
    athlete_id,
    DATE(start_date_local) AS date,
    SUM(distance) / 1000.0 AS distance_km
FROM activities
GROUP BY athlete_id, DATE(start_date_local);

-- Monthly activity aggregation by sport type
CREATE VIEW v_monthly_stats AS
SELECT
    athlete_id,
    strftime('%Y-%m', start_date_local) AS month,
    sport_type,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y-%m', start_date_local), sport_type;

-- Yearly activity aggregation
CREATE VIEW v_yearly_stats AS
SELECT
    athlete_id,
    CAST(strftime('%Y', start_date_local) AS INTEGER) AS year,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y', start_date_local);

-- Weekly activity aggregation
CREATE VIEW v_weekly_stats AS
SELECT
    athlete_id,
    strftime('%Y-W%W', start_date_local) AS week,
    strftime('%Y-%m-%d', start_date_local, 'weekday 0', '-6 days') AS week_start,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(total_elevation_gain), 0) AS total_elevation
FROM activities
GROUP BY athlete_id, strftime('%Y-W%W', start_date_local);

-- Gear usage statistics
CREATE VIEW v_gear_monthly_usage AS
SELECT
    g.id AS gear_id,
    g.name AS gear_name,
    g.source,
    g.hashtag,
    g.retired,
    g.purchase_price,
    g.purchase_currency,
    g.athlete_id,
    strftime('%Y-%m', a.start_date_local) AS month,
    COUNT(*) AS activity_count,
    COALESCE(SUM(a.distance), 0) AS distance,
    COALESCE(SUM(a.moving_time), 0) AS moving_time
FROM gear g
LEFT JOIN activities a ON a.gear_id = g.id AND a.athlete_id = g.athlete_id
GROUP BY g.id, strftime('%Y-%m', a.start_date_local);

-- Calendar day statistics
CREATE VIEW v_calendar_days AS
SELECT
    athlete_id,
    DATE(start_date_local) AS date,
    COUNT(*) AS activity_count,
    COALESCE(SUM(distance), 0) AS total_distance,
    COALESCE(SUM(moving_time), 0) AS total_time,
    COALESCE(SUM(calories), 0) AS total_calories
FROM activities
GROUP BY athlete_id, DATE(start_date_local);
`,
  },
  {
    version: 3,
    name: "maintenance_log_unique",
    sql: `-- Add unique constraint for maintenance_log to support ON CONFLICT clause
-- This prevents duplicate maintenance entries for the same component at the same time

CREATE UNIQUE INDEX IF NOT EXISTS idx_maintenance_log_component_completed
    ON maintenance_log(component_id, completed_at);
`,
  },
  {
    version: 4,
    name: "notification_history",
    sql: `-- Notification history table to track which achievements have been notified
-- This prevents duplicate notifications when the same achievements are detected during re-import

CREATE TABLE IF NOT EXISTS notification_history (
    id INTEGER PRIMARY KEY,
    athlete_id INTEGER NOT NULL,
    achievement_type TEXT NOT NULL,
    achievement_key TEXT NOT NULL,
    notified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Unique constraint to prevent duplicate notifications
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_history_unique
    ON notification_history(athlete_id, achievement_type, achievement_key);

-- Index for efficient lookups by athlete
CREATE INDEX IF NOT EXISTS idx_notification_history_athlete
    ON notification_history(athlete_id);
`,
  },
  {
    version: 5,
    name: "zone_distribution",
    sql: `-- Activity zone distribution table to store HR zone time per activity
-- Enables fast aggregation for zone trend charts without recalculating from HR streams

CREATE TABLE IF NOT EXISTS activity_zone_distributions (
    activity_id INTEGER PRIMARY KEY REFERENCES activities(id) ON DELETE CASCADE,
    zone_def_id TEXT NOT NULL,  -- "sport_type:effective_from" for invalidation tracking
    seconds_z1 INTEGER NOT NULL DEFAULT 0,
    seconds_z2 INTEGER NOT NULL DEFAULT 0,
    seconds_z3 INTEGER NOT NULL DEFAULT 0,
    seconds_z4 INTEGER NOT NULL DEFAULT 0,
    seconds_z5 INTEGER NOT NULL DEFAULT 0,
    total_seconds INTEGER NOT NULL DEFAULT 0,
    computed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Note: No index needed on activity_id - PRIMARY KEY already creates one

-- Index on zone_def_id for potential future use:
-- - Direct invalidation by zone definition (e.g., when deleting a specific definition)
-- - Querying which activities used a particular zone definition
-- Currently unused but kept for forward compatibility.
CREATE INDEX IF NOT EXISTS idx_zone_dist_zone_def ON activity_zone_distributions(zone_def_id);
`,
  }
]
