// Code generated by scripts/generate-constants. DO NOT EDIT.

package shared

const (
	EddingtonNextSteps         = 5
	ImportEventBatchSize       = 25
	ImportEventFlushIntervalMs = 2000
	MaxGearPrice               = 999999.99
	PaginationDefaultPage      = 1
	PaginationDefaultPerPage   = 50
	PaginationMaxPage          = 10000
	PaginationMaxPerPage       = 200
	TrainingLoadAtlTauDays     = 7
	TrainingLoadCtlTauDays     = 42
)

var (
	PowerDurationsS = []int{5, 10, 30, 60, 300, 480, 1200, 3600}
)
